---
# tasks to complete before running roles
- name: Pre-run to update package cache
  hosts: all
  connection: local
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache Ubuntu
      tags: always
      apt:
        upgrade: yes
        update_cache: yes
      changed_when: false

# run roles
- name: Base role for all systems
  hosts: all
  tags: base
  become: true
  roles:
    - base

- name: Workstation role
  hosts: workstation
  tags: workstation
  become: true
  roles:
    - workstation


# - name: Server role
#  hosts: server
#  tags: server
#  become: true
#  roles:
#    - server

# end of run cleanup and reporting
- name: Cleanup and reporting
  hosts: all
  become: true

  tasks:
    - include_tasks: pre_post_tasks/cleanup.yml
    - include_tasks: pre_post_tasks/send_completion_alert.yml
      tags: always
      when:
        - task_failed is not defined

    - include_tasks: pre_post_tasks/send_failure_alert.yml
      tags: always
      when:
        - task_failed is defined
#       - task_failed == true
