---
# tasks to complete before running roles
- name: Pre-run to update package cache
  hosts: all
  connection: local
  tags: always
  become: true
  become_method: sudo

  pre_tasks:
    - name: Pre-run | update package cache Ubuntu
      tags: always
      apt:
        upgrade: true
        update_cache: true
      changed_when: false

# run base roles, if task_failed not defined
- name: Base role for all systems
  hosts: all
  tags: base
  become: true
  become_method: sudo

  roles:
    - base

- name: Display msg
  hosts: all
  tasks:
    debug: 
      msg: "Workstation role commented out"
# run workstation roles, if task_failed not defined
#- name: Workstation role
#  hosts: workstation
#  tags: workstation
#  become: true
#  become_method: sudo

#  roles:
#    - workstation

# - name: Server role
#  hosts: server
#  tags: server
#  become: true
#  roles:
#    - server

# end of run reporting
- name: Reporting
  hosts: all
  become: true
  become_method: sudo

  tasks:

    - name: End of Tasks | Print completion notification
      tags: always
      debug:
        msg: "\n
          *-------------------------------------------------------\n
          *Task*: ✔️  Ansible provision finished on *{{ ansible_hostname }}*\n
          *-------------------------------------------------------"
      changed_when: False
      when:
        - task_failed is not defined

    - name: End of Tasks | Print failure notification
      tags: always
      debug:
        msg: "⚠️  Ansible provision failed on *{{ ansible_hostname }}*\n\n
          *Task*:  {{ ansible_failed_task.name }}\n
          *Action*: {{ ansible_failed_task.action }}\n
          *Error Message*: \n ```{{ ansible_failed_result | to_nice_json }}```"
      changed_when: False
      when:
        - task_failed is defined
        - task_failed
