---
- name: Gnome | desktop block
  become: true
  become_method: sudo
  block:
    - name: Gnome | desktop | copy wallpaper file
      copy:
        src: gnome/saturn.png
        dest: /usr/share/backgrounds/budgie/saturn.png
        owner: root
        group: root
        mode: 0644

    - name: Gnome | desktop | set wallpaper
      community.general.dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/budgie/saturn.png'"

    - name: Gnome | desktop | disable touchpad
      community.general.dconf:
        key: "/org/gnome/desktop/peripherals/touchpad/{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: 'send-events', value: "'disabled'" }

    - name: Gnome | desktop | copy lock screen background file
      copy:
        src: gnome/jupiter.jpg
        dest: /usr/share/backgrounds/budgie/jupiter.jpg
        owner: root
        group: root
        mode: 0644

    - name: Gnome | desktop | set interface values
      community.general.dconf:
        key: "/org/gnome/desktop/interface/{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: 'color-scheme', value: "'prefer-dark'" }
        - { key: 'cursor-size', value: '48' }
        - { key: 'cursor-theme', value: "'DMZ-Black'" }
        - { key: 'gtk-theme', value: "'QogirBudgie-dark'" }
        - { key: 'icon-theme', value: "'Humanity-Dark'" }
        - { key: 'text-scaling-factor', value: '1.20' }

    - name: Gnome | gedit | set editor values
      community.general.dconf:
        key: "/org/gnome/gedit/preferences/editor/{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: 'scheme', value: "'cobalt'" }
        - { key: 'tabs-size', value: "'uint32 4'" }
