---
- name: gnome | plank | set alignment, size, zoom
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/net/launchpad/plank/docks/dock1/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: 'alignment', value: "'center'" }
    - { key: 'icon-size', value: '70' }
    - { key: 'theme', value: "'Default'" }
    - { key: 'zoom-percent', value: '160' }
