---
- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart udisks2
  ansible.builtin.service:
    name: udisks2
    state: restarted

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
