---
- name: restart_sshd
  service:
    name: ssh
    state: restarted

- name: restart_udisks2
  service:
    name: udisks2
    state: restarted

- name: update_vim_bundle_perms
  file:
    path: /home/bernhard/.vim/bundle
    owner: bernhard
    group: users
    recurse: true

- name: restart_journald
  service:
    name: systemd-journald
    state: restarted
