---
- name: restart_sshd
  service:
    name: ssh
    state: restarted

- name: restart_udisks2
  service:
    name: udisks2
    state: restarted

- name: restart_journald
  service:
    name: systemd-journald
    state: restarted
