---
- name: Restart_sshd
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart_udisks2
  ansible.builtin.service:
    name: udisks2
    state: restarted

- name: Restart_journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Update_xdg
  become_user: "{{ user_name }}"
  ansbible.builtin.command: xdg-user-dirs-update
