---
- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: ssh
    state: restarted

- name: update_vim_bundle_perms
  file:
    path: /home/bpic/.vim/bundle
    owner: bpic
    group: users
    recurse: true
