---
- name: users | bernhard | copy profile image
  tags: dotfiles,dotfiles-bernhard
  become: yes
  become_method: sudo
  copy:
    src: users/bernhard/bernhard.jpg
    dest: /var/lib/AccountsService/icons/bernhard.jpg
    owner: root
    group: root
    mode: 0644

- name: users | bernhard | copy keepassxc ini file
  tags: dotfiles,dotfiles-bernhard
  become: yes
  become_method: sudo
  copy:
    src: users/bernhard/keepassxc_config
    dest: /home/bernhard/snap/keepassxc/current/.config/keepassxc/keepassxc.ini
    owner: bernhard
    group: users
    mode: 0644
