---
- name: Users | bernhard block
  when:
    - bernhard is defined
    - bernhard
  block:
    - name: Users | bernhard | copy profile image
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.copy:
        src: users/bernhard/bernhard.jpg
        dest: /var/lib/AccountsService/icons/bernhard.jpg
        owner: root
        group: root
        mode: 0644
