#!/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

export TERM=xterm-256color
# GREP_COLORS see https://www.gnu.org/software/grep/manual/grep.html#index-GREP_005fCOLORS-environment-variable
export GREP_COLORS='sl=97;48;5;236:cx=37;40:mt=30;48;5;186:fn=38;5;197:ln=38;5;154:bn=38;5;141:se=38;5;81' # monokai-based

## editor
export EDITOR=vim
export VISUAL=vim

## history
export HISTFILE=$HOME/.history
export HISTSIZE=10000
export SAVEHIST=10000

## XDG
# Set up a few standard directories based on:
#   https://wiki.archlinux.org/title/XDG_Base_Directory

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

## zsh
export ZDOTDIR=$HOME/.config/zsh

## path
export PATH=~/bin:$PATH
