#!/bin/env zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

export TERM=xterm-256color
# GREP_COLORS see https://www.gnu.org/software/grep/manual/grep.html#index-GREP_005fCOLORS-environment-variable
export GREP_COLORS='sl=97;48;5;236:cx=37;40:mt=30;48;5;186:fn=38;5;197:ln=38;5;154:bn=38;5;141:se=38;5;81' # monokai-based

## editor
export EDITOR=vim
export VISUAL=vim

## XDG
# Set up a few standard directories based on:
#   https://wiki.archlinux.org/title/XDG_Base_Directory

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

## zsh
export ZDOTDIR=$HOME/.config/zsh

## vagrant
export VAGRANT_HOME=/mnt/k8s
export VAGRANT_DEFAULT_PROVIDER=libvirt

#<-- BEGIN Inserted by local_k8s_config.yml Ansible-Playbook -->
## Kubernetes
export KUBECONFIG=/home/bernhard/.kube/lxd.conf
#<-- END Inserted by local_k8s_config.yml Ansible-Playbook -->

## history
# setopt are defined in history.zsh file
# ignore duplicate lines in the history.
# ignore commands that  start with space `ignorespace'.
export HISTFILE=$ZDOTDIR/.zsh_history
export HISTSIZE=10000
export HISTFILESIZE=10000

## path
# $HOME/bin is added to PATH in .profile, so not required to add here
# ... if $HOME/.local/bin exists its required for LunarVim and others
# sample if more than one directory:  "for mydir in $HOME/.cargo/bin $HOME/.local/bin; do"
for mydir in $HOME/.local/bin; do
    if [ -d $mydir ]; then
        case ":$PATH:" in
          *":${mydir}:"*)   # directory already in PATH, do nothing
            ;;
          *) 
            PATH=${mydir}:$PATH
            ;;
        esac
    fi
done

