---
- name: Users | root | ensure account is locked
  user:
    name: root
    password_lock: true

- name: Users | root | create config directories
  file:
    path: /root/{{ item.dir }}
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
    - { dir: '.vim' }
    - { dir: '.vim/colors' }

- name: Users | root | copy dotfiles
  copy:
    src: users/{{ item.src }}
    dest: /root/{{ item.dest }}
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'bash/root-bashrc', dest: '.bashrc' }
    - { src: 'bash/bash_aliases', dest: '.bash_aliases' }
    - { src: 'bash/bash_functions', dest: '.bash_functions' }
    - { src: 'bash/dircolors', dest: '.dircolors' }
    - { src: 'vim/vimrc-root', dest: '.vimrc' }
