---
- name: Users | root | ensure account is locked
  ansible.builtin.user:
    name: root
    password_lock: true

- name: Users | root | create config directories for vim and zsh
  ansible.builtin.file:
    path: /root/{{ item.dir }}
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
    - { dir: '.config/zsh' }
    - { dir: '.vim' }
    - { dir: '.vim/colors' }

- name: Users | root | copy dotfiles
  ansible.builtin.copy:
    src: users/{{ item.src }}
    dest: /root/{{ item.dest }}
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'bash/root-bashrc', dest: '.bashrc' }
    - { src: 'bash/bash_aliases', dest: '.bash_aliases' }
    - { src: 'bash/bash_functions', dest: '.bash_functions' }
    - { src: 'bash/dircolors', dest: '.dircolors' }
    - { src: 'vim/vimrc-root', dest: '.vimrc' }

- name: Users | zap | Download install script zap (plugin manager for zsh)
  ansible.builtin.shell: |
    set -o pipefail
    curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh \ 
      --output /tmp/zap-install.zsh
  args:
    executable: /bin/zsh
  register: zap_load
  changed_when: zap_load.rc == 0

- name: Users | zap | Change permission of scripts
  ansible.builtin.file:
    path: /tmp/{{ item }}
    state: file
    owner: root
    group: root
    mode: 0755
  with_items:
    - zap-install.zsh

- name: Users | zap | install zsh plugin manager (zap)
  ansible.builtin.script: /tmp/zap-install.zsh --branch release-v1
  register: zap_install
  changed_when: zap_install.rc == 0

- name: Users | Zsh | copy individual zsh config files for root
  ansible.builtin.copy:
    src: zsh/{{ item.src }}
    dest: /root/.config/zsh/{{ item.dest }}
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'aliases.zsh', dest: 'aliases.zsh' }
    - { src: 'history.zsh', dest: 'history.zsh' }
    - { src: 'root-prompt.zsh', dest: 'prompt.zsh' }
    - { src: 'functions.zsh', dest: 'functions.zsh' }
    - { src: 'zshrc', dest: '.zshrc' }

- name: Users | Zsh | copy dotfiles for root
  ansible.builtin.copy: 
    src: zsh/{{ item.src }}
    dest: /root/{{ item.dest }}
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'zshenv', dest: '.zshenv' }
