---
- name: Users | root | ensure account is locked
  ansible.builtin.user:
    name: root
    password_lock: true

- name: Users | root | create config directories for vim and zsh
  ansible.builtin.file:
    path: /root/{{ item.dir }}
    state: directory
    owner: root
    group: root
    mode: "0700"
  with_items:
    - { dir: '.vim' }
    - { dir: '.vim/colors' }

- name: Users | root | copy dotfiles from user bernhard
  ansible.builtin.copy:
    src: /home/bernhard/{{ item.src }}
    dest: /root/{{ item.dest }}
    owner: root
    group: root
    mode: "0600"
  with_items:
    - { src: '.bash_aliases', dest: '.bash_aliases' }
    - { src: '.bash_functions', dest: '.bash_functions' }
    - { src: '.dircolors', dest: '.dircolors' }

- name: Users | root | copy individual bash prompt
  ansible.builtin.copy:
    src: users/{{ item.src }}
    dest: /root/{{ item.dest }}
    owner: root
    group: root
    mode: "0600"
  with_items:
    - { src: 'bash/root-bashrc', dest: '.bashrc' }
    - { src: 'vim/vimrc-root', dest: '.vimrc' }

- name: Users | root | import tasks for zsh
  become: true
  become_user: root
  ansible.builtin.import_tasks: ../software/zsh-root.yml
