---
- name: Ubuntu user block
  when:
    - ubuntu is defined
    - ubuntu
  block:
    - name: Update ubuntu user's Password
      ansible.builtin.user:
        name: ubuntu
        update_password: always
        password: "{{ ubuntu_passwd }}"
