---
- name: btop block
  block:
    - name: system_setup | btop++ | download latest release info
      shell: |
        set -o pipefail
        curl --silent "https://api.github.com/repos/aristocratos/btop/releases/latest" |
        jq -r .tag_name
      args:
        executable: /bin/bash
      register: btop_release
      changed_when: btop_release.rc == 0

    - name: system_setup | btop++ | install latest btop++ binary
      ansible.builtin.unarchive:
        src: https://github.com/aristocratos/btop/releases/download/{{ btop_release.stdout }}/btop-x86_64-linux-musl.tbz
        dest: /usr/local/bin/btop
        remote_src: yes
        mode: 0755
        owner: root
        group: root

  become: true
  become_method: sudo
