---
#
# find the correct GFXMODE:
# install hwinfo and run:
#  sudo hwinfo --framebuffer
#

# don't install and use grub-customizer - with installed themes of no use anymore

#- name: system-setup | grub | add ppa repository
#  apt_repository:
#    filename: grubcustomizer
#    repo: ppa:danielrichter2007/grub-customizer
#    state: present
#    update_cache: yes

# run "sudo apt-key list" to find the full public gpg key
# use the last 8 characters for the export command

#    - name: software | grub | apt-key deprecated - convert trusted.gpg into member in tursted.gpg.d
#      shell: |
#        set -o pipelfail 
#        apt-key export 3F055C03 | \
#        gpg --dearmour -o /etc/apt/trusted.gpg.d/grub-customizer.gpg
#      args:
#        warn: false
#        executalbe: /bin/bash
#      register: gpg_convert
#      changed_when: gpg_convert.rc == 0

        
- name: system-setup | grub | install grub
  apt:
    pkg:
#      - grub-customizer
      - grub2-splashimages
    state: present

- name: system-setup | grub block for {{ inventory_hostname }}
  block:
    - name: system-setup | grub | copy background images for grub
      copy:
        src: grub/{{ item.src }}
        dest: /usr/share/images/{{ item.dest }}
        owner: root
        group: root
        mode: 0644
      with_items:
        - { src: 'black-hole-blue.tga', dest: 'black-hole-blue.tga' }
        - { src: 'saturn-wallpaper.jpg', dest: 'saturn.jpg' }
        - { src: 'CarinaNebula.png', dest: 'CarinaNebula.png' }
        - { src: 'QuasarEarlyUniverse.jpg', dest: 'QuasarEarlyUniverse.jpg' }
        - { src: 'QuasarOutflow.png', dest: 'QuasarOutflow.png' }
        - { src: 'SouthernRingNebula.png', dest: 'SouthernRingNebula.png' }
        - { src: 'StephansQuintetGalaxies.png', dest: 'StephansQuintetGalaxies.png' }

    - name: system_setup | grub | checkout git dark-matter repository
      git:
        repo: https://gitlab.com/VandalByte/darkmatter-grub-theme.git
        dest: /tmp/grub-darkmatter
        force: true
        version: main

#    - name: system_setup | grub | checkout git virtual-future repository
#      git:
#        repo: https://gitlab.com/deck451/virtual_future_grub_theme.git
#        dest: /tmp/grub-virtualfuture
#        force: true
#        version: main

    - name: system_setup | grub | create themes directory
      file:
        path: /boot/grub/themes
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: system_setup | grub | copy grub themes
      copy:
        src: /tmp/{{ item }}
        dest: /boot/grub/themes
        owner: root
        group: root
        mode: 0644
      with_items:
        - 'grub-darkmatter'
#        - 'grub-virtualfuture/virtual-future'

    - name: system_setup | grub | copy png file ubuntu to background
      copy:
        src: /tmp/grub-darkmatter/assets/backgrounds/ubuntu-1440p.png
        dest: /boot/grub/themes/grub-darkmatter/background.png
        owner: root
        group: root
        mode: 0644

#
# acpi stands for: "Advanded Configuration and Power Interface"
# error messages in log: "EISA: cannot allocate resource for Mainboard"
#
    - name: system_setup | grub | Replace CMDLINE with acpi=off to supress error messages
      replace:
        path: /etc/default/grub
        regexp: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
        replace: 'GRUB_CMDLINE_LINUX_DEFAULT="acpi=off"'

    - name: system_setup | grub | Insert background line in grub file
      lineinfile:
        path: /etc/default/grub
        insertafter: '^#GRUB_GFXMODE='
        line: 'GRUB_GFXMODE=3840x2160x24,auto'

    - name: system_setup | grub | add lines for BACKGROUND, THEME, GFXPAYLOAD_LINUX and DISABLE_OS_PROBER
      lineinfile:
        dest: /etc/default/grub
        line: '{{ item }}'
      with_items:
        - 'GRUB_BACKGROUND="/usr/share/images/grub/saturn.jpg"'
        - 'GRUB_THEME="/boot/grub/themes/dark-matter/theme.txt"'
        - 'GRUB_GFXPAYLOAD_LINUX="keep"'
        - 'GRUB_DISABLE_OS_PROBER="false"'

    - name: system_setup | grub | update grub configuration
      command: update-grub
      register: grub_updcmd
      changed_when: grub_updcmd.rc == 0

  become: yes
  become_method: sudo
  when: "'bequiet' in inventory_hostname"

- name: system-setup | grub block for {{ inventory_hostname }}
  block:
    - name: system-setup | grub | copy black hole file
      copy:
        src: grub/black-hole-blue.tga
        dest: /usr/share/images/grub/black-hole-blue.tga
        owner: root
        group: root
        mode: 0644

    - name: system_setup | grub | checkout git distro-grub-themes repository
      git:
        repo: https://github.com/AdisonCavani/distro-grub-themes.git
        dest: /tmp/grub-theme
        force: true
        version: master

    - name: system_setup | grub | create themes directory
      file:
        path: /boot/grub/themes
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: system_setup | grub | copy distro-grub-themes for acer
      copy:
        src: /tmp/grub-theme/customize/acer
        dest: /boot/grub/themes
        owner: root
        group: root
        mode: 0644

#
# acpi stands for: "Advanded Configuration and Power Interface"
# error messages in log: "EISA: cannot allocate resource for Mainboard"
#
    - name: system_setup | grub | Replace CMDLINE with acpi=off to supress error messages
      replace:
        path: /etc/default/grub
        regexp: 'GRUB_CMDLINE_LINUX_DEFAULT=""'
        replace: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash acpi=off"'

    - name: system_setup | grub | Insert background line
      lineinfile:
        path: /etc/default/grub
        insertafter: '^#GRUB_GFXMODE='
        line: 'GRUB_GFXMODE=1024x768x32'

    - name: system_setup | grub | lines for BACKGROUND, THEME, GFXPAYLOAD_LINUX and DISABLE_OS_PROBER
      lineinfile:
        dest: /etc/default/grub
        line: '{{ item }}'
      with_items:
        - 'GRUB_BACKGROUND="/usr/share/images/grub/black-hole-blue.tga.jpg"'
        - 'GRUB_THEME="/boot/grub/themes/distro-grub-themes/acer/theme.txt"'
        - 'GRUB_GFXPAYLOAD_LINUX="keep"'
        - 'GRUB_DISABLE_OS_PROBER="false"'

    - name: system_setup | grub | update grub configuration
      command: update-grub
      register: grub_updcmd
      changed_when: grub_updcmd.rc == 0

  become: yes
  become_method: sudo
  when: "'acermsch' in inventory_hostname"
