---
- name: system_setup | ipscan | get the latest version of ipscan software
  shell: |
    set -o pipefail
    curl --silent https://api.github.com/repos/angryip/ipscan/releases/latest | \
    jq -r .tag_name
  args:
    executable: /bin/bash
  register: ipscan_version
  changed_when: ipscan_version.rc == 0

- name: system_setup | ipscan | print version
  debug:
    var: ipscan_version.stdout
    verbosity: 2

- name: system_setup | ipscan | install the ipscan deb package
  become: true
  become_method: sudo
  ansible.builtin.apt:
    deb: https://github.com/angryip/ipscan/releases/download/{{ ipscan_version.stdout }}/ipscan_{{ ipscan_version.stdout }}_amd64.deb
