---
- name: system-setup wifi block
  tags: wifi
  block:

    - name: connect to wlps130 with nmcli command
      become: yes
      become_method: sudo
      command: nmcli dev wifi connect WiFi-bpic password "{{ wifi_passwd }}"
      register: wifi_result
      changed_when: wifi_result.rc == 0
    
    - name: print nmcli result
      debug:
        var: wifi_result
        verbosity: 2

  become: yes
  become_user: root
