---
- name: software | calibre e-book block
  block:
    - name: software | install calibre
      apt:
        pkg:
          - calibre
        state: present

  when:
    - calibre is defined
    - calibre
