---
- name: Software | calibre e-book block
  when:
    - calibre is defined
    - calibre
  block:
    - name: Software | install calibre
      apt:
        pkg:
          - calibre
        state: present
