---
- name: software | calibre e-book block
  block:
    - name: software | install librecad
      apt:
        pkg:
          - calibre
        state: present

  when:
    - librecad is defined
    - librecad

