---
- name: print filesearch variable from host_vars
  debug:
    var: filesearch

- name: Add fsearch repository into sources list
  apt_repository:
    repo: 'deb http://ppa.launchpad.net/christian-boxdoerfer/fsearch-stable/ubuntu {{ ansible_distribution_release }} main'
    state: present
  when:
    - filesearch is defined
    - filesearch == "yes"

- name: software | install fsearch
  tags: packages,workstation-packages
  apt:
    update_cache: true
    pkg:
      - fsearch
    state: present
  when:
    - filesearch is defined
    - filesearch  == "yes"
