---
- name: software | fsearch block
  block:
    - name: software | fsearch | add repository the old way
      become: yes
      become_method: sudo
      command: add-apt-repository ppa:christian-boxdoerfer/fsearch-stable

#    - name: software | fsearch | add repository into sources list
#      apt_repository:
#        repo: 'deb http://ppa.launchpad.net/christian-boxdoerfer/fsearch-stable/ubuntu/ {{ ansible_distribution_release }} main'
#        state: present

    - name: software | install fsearch
      tags: packages,workstation-packages
      apt:
        update_cache: true
        pkg:
          - fsearch
        state: present

    - name: software | fsearch | create config/fsearch directory
      tags: bernhard,yamllint,sudo,users
      file:
        path: /home/bernhard/{{ item.dir }}
        state: directory
        owner: bernhard
        group: users
        mode: 0700
      with_items:
        - { dir: '.config/fsearch' }

    - name: software | fsearch | copy config file
      copy:
        src: users/bernhard/{{ item.src }}
        dest: /home/bernhard/{{ item.dest }}
        owner: bernhard
        group: users
        mode: 0600
      with_items:
        - { src: 'fsearch_config', dest: '.config/fsearch/fsearch.conf' }
  when:
    - filesearch is defined
    - filesearch

