---
- name: Software | install misc game packages
  when:
    - games is defined
    - games
  ansible.builtin.apt:
    pkg:
      - extremetuxracer
      - frozen-bubble
      - gnome-chess
      - supertux
      - supertuxkart
      - wesnoth
      - flightgear
    state: present
