---
- name: Software | gimp block
  become: true
  become_method: ansible.builtin.sudo
  when:
    - gimp is defined
    - gimp
  block:

    - name: Software | gimp | install gimp, gegl and dependencies
      ansible.builtin.apt:
        pkg:
          - gimp
          - gegl
          - gimp-help-en
          - gimp-data-extras
        state: present

    - name: Software | gimp | start gimp for configuration and create .config/GIMP structure
      ansible.builtin.command:
        cmd: gimp-3.0
      timeout: 10
      ignore_errors: true
      register: gimp_result
      changed_when: gimp_result.rc == 0

    - name: Software | gimp | print result from command
      ansible.builtin.debug:
        var: gimp_result
        verbosity: 2

    - name: Sofware | gimp | creates directory tree for .config/GIMP/3.0/plug-ins/arrowdesigner and scripts
      ansible.builtin.file:
        path: /home/{{ user_name }}/{{ item.dir }}
        state: directory
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        mode: "0755"
      with_items:
        - { dir: '.config/GIMP/{{ gimp_subdir_version }}/plug-ins/arrowdesigner' }
        - { dir: '.config/GIMP/{{ gimp_subdir_version }}/scripts' }

    - name: Users | bernhard | download arrowdesigner.py, install arrowdesigner and make it executable
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/{{ item.url }}"
        dest: "/home/{{ user_name }}/.config/GIMP/3.0/plug-ins/arrowdesigner/{{ item.dest }}"
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        mode: "0755"
      with_items:
        - { url: 'akkana/gimp-plugins/refs/heads/master/gimp3/arrowdesigner.py', dest: 'arrowdesigner.py' }
    - name: Software | gimp | copy arrow_V3.scm file from /mnt/Data/gimp/scripts
      ansible.builtin.copy:
        src: /mnt/Data/gimp/scripts/arrow_V3.scm
        dest: /home/{{ user_name }}/.config/GIMP/3.0/scripts/arrow_V3.scm
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        mode: "0755"
