---
- name: software | gimp block
  tags: gimp
  block:

#    - name: software | gimp | add gimp apt repository and update | check if latest ubuntu release available
#      apt_repository:
#        filename: gimp
#        repo: 'ppa:ubuntuhandbook1/gimp'
#        state: present
#        update_cache: yes

    - name: software | gimp | install gimp & gegl
      apt:
        pkg:
          - gimp
          - gegl
        state: present

    - name: gnome | desktop | create gimp directories in .config
      file:
        path: /home/{{ user_name }}/{{ item.dir }}
        state: directory
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        mode: 0755
      with_items:
        - { dir: '.config/GIMP' }
        - { dir: '.config/GIMP/{{ gimp_subdir_version }}' }

    - name: software | gimp | copy gimprc & text-tool files
      copy:
        src: gimp/{{ item.src }}
        dest: /home/bernhard/.config/GIMP/{{ gimp_subdir_version }}/{{ item.dest }}
        owner: bernhard
        group: users
        mode: 0664
      with_items:
        - { src: 'gimprc', dest: 'gimprc' }
#       - { src: 'gimp-text-tool', dest: 'tool-options/gimp-text-tool' }

  become: yes
  become_method: sudo
  when:
    - gimp is defined
    - gimp
