---
- name: software | keepassxc block
  tags: keepassxc
  block:

    - name: software | keepassxc | add keepassxc apt repository
      apt_repository:
        repo: 'ppa:phoerious/keepassxc'
        state: present
        filename: keepassxc
        update_cache: yes

# run "sudo apt-key list" to find the full public gpg key
# use the last 8 characters for the export command

    - name: software | keepassxc | apt-key deprecated - convert trusted.gpg into member in tursted.gpg.d
      shell: |
        set -o pipefail
        apt-key export 0068FCD6 | \
        gpg --dearmour -o /usr/share/keyrings/keepassxc.gpg
      args:
        executable: /bin/bash
      register: gpg_convert
      changed_when: gpg_convert.rc == 0

    - name: software | keepassxc | install keepassxc
      apt:
        pkg:
          - keepassxc

  become: yes
  become_method: sudo
  when:
    - keepassxc is defined
    - keepassxc
