---
- name: software | keepassxc block
  tags: keepassxc
  block:

    - name: software | keepassxc | add keepassxc apt repository
      apt_repository:
        filename: keepassxc
        repo: 'ppa:phoerious/keepassxc'
        state: present
        update_cache: yes

    - name: software | keepassxc | install keepassxc
      apt:
        pkg:
          - keepassxc

  become: yes
  become_method: sudo
  when:
    - keepassxc is defined
    - keepassxc
