---
- name: software | kvm | install cpu-checker prerequisite
  apt:
    name:
      - cpu-checker

- name: software | kvm | check system for kvm
  command: kvm-ok
  register: kvm_result
  changed_when: "'KVM acceleration can be used' in kvm_result.stdout"

- name: software | kvm | install kvm and dependencies
  apt:
    name:
      - qemu
      - qemu-kvm
      - libvirt-bin
      - libvirt-daemon
      - libvirt-clients
      - virt-manager
      - virt-viewer
      - bridge-utils
  when:
    - kvm is defined
    - kvm
    - "'KVM acceleration can be used' in kvm_result.stdout"

- name: software | kvm | add groups to user bernhard
  user:
    name: bernhard
    groups: libvirt,kvm
    append: yes
  become: yes
  become_method: sudo
