---
#
#  install info from: https://computingforgeeks.com/install-kvm-centos-rhel-ubuntu-debian-sles-arch/
#
- name: software | kvm block
  block:
    - name: software | kvm | install cpu-checker prerequisite
      apt:
        name: cpu-checker

    - name: software | kvm | check system for kvm
      command: kvm-ok
      register: kvm_result
      changed_when: "'KVM acceleration can be used' in kvm_result.stdout"

    - name: software | kvm | install kvm and dependencies
      apt:
        pkg:
          - qemu
          - qemu-kvm
          - libvirt-daemon
          - libvirt-clients
          - virt-manager
          - virt-viewer
          - bridge-utils
        state: present
      when:
        - "'KVM acceleration can be used' in kvm_result.stdout"
        
     - name: Insert vhost-net in /etc/modules
       become_method: sudo
       become: yes
       lineinfile:
         dest: /etc/modules
         line: 'vhost-net'        

    - name: software | kvm | add groups libvirt, kvm to user bernhard
      become: yes
      become_method: sudo
      user:
        name: bernhard
        groups: libvirt,kvm
        append: yes
      when:
        - "'KVM acceleration can be used' in kvm_result.stdout"

    - name: software | kvm | create config/libvirt directory
       file:
        path: /home/bernhard/{{ item.dir }}
        state: directory
        owner: bernhard
        group: users
        mode: 0740
      with_items:
        - { dir: '.config/libvirt' }

    - name: software | kvm | copy libvirt config file
      copy:
        src: users/bernhard/{{ item.src }}
        dest: /home/bernhard/{{ item.dest }}
        owner: bernhard
        group: users
        mode: 0640
      with_items:
        - { src: 'libvirt_config', dest: '.config/libvirt/libvirt.conf'

    - name: system_setup | fstab | add x-gvfs-show to options
      tags: systemd,fstab,swapfile
      replace:
        path: /home/bernhard/.config/libvirt/libvirt.conf
        regexp: "{{ item.regexp }}"
        replace: "{{ item.value }}"
      with_items:
        - { regexp: '#uri_default', value: 'uri_default' }

  when:
    - kvm is defined
    - kvm

