---
- name: Software | librecad block
  when:
    - librecad is defined
    - librecad
  block:
    - name: Software | install librecad
      apt:
        pkg:
          - librecad
        state: present

    - name: Software | librecad | create config/librecad directory
      file:
        path: /home/bernhard/{{ item.dir }}
        state: directory
        owner: bernhard
        group: users
        mode: 0740
      with_items:
        - { dir: '.config/LibreCAD' }

    - name: Software | librecad | copy config file
      copy:
        src: users/bernhard/{{ item.src }}
        dest: /home/bernhard/{{ item.dest }}
        owner: bernhard
        group: users
        mode: 0640
      with_items:
        - { src: 'librecad_config', dest: '.config/LibreCAD/LibreCAD.conf' }
