---
- name: software | librecad block
  block:
    - name: software | install librecad
      tags: packages,workstation-packages
      apt:
        update_cache: true
        pkg:
          - librecad
        state: present

    - name: software | librecad | create config/librecad directory
      tags: bernhard,yamllint,sudo,users
      file:
        path: /home/bernhard/{{ item.dir }}
        state: directory
        owner: bernhard
        group: users
        mode: 0700
      with_items:
        - { dir: '.config/LibreCAD' }

    - name: software | librecad | copy config file
      copy:
        src: users/bernhard/{{ item.src }}
        dest: /home/bernhard/{{ item.dest }}
        owner: bernhard
        group: users
        mode: 0600
      with_items:
        - { src: 'librecad_config', dest: '.config/LibreCAD/LibreCAD.conf' }
  when:
    - librecad is defined
    - librecad

