---
- name: Software multimedia block
  when:
    - media is defined
    - media
  block:
    - name: Software | install multimedia codecs
      apt:
        pkg:
          - pavucontrol
          - gstreamer1.0-plugins-bad
          - libdvd-pkg
        state: present

    - name: Software | Reconfigure libdvd-pkg
      become: yes
      become_method: sudo
      command: dpkg-reconfigure libdvd-pkg
      register: media_cmd
      changed_when: media_cmd.rc == 0

# https://github.com/ginsys/ansible-plugins/blob/devel/library/dpkg_reconfigure
