---
- name: software multimedia block
  block:
    - name: software | install multimedia codecs
      apt:
        pkg:
          - pavucontrol
          - gstreamer1.0-plugins-bad
          - libdvd-pkg
        state: present

    - name: software | Reconfigure libdvd-pkg
      become: yes
      become_method: sudo
      command: dpkg-reconfigure libdvd-pkg

  when:
    - media is defined
    - media

# https://github.com/ginsys/ansible-plugins/blob/devel/library/dpkg_reconfigure
