---
- name: software | install workstation distribution packages
  tags: packages,workstation-packages
  apt:
    pkg:
      - geany
      - gparted
      - p7zip-full
      - openvpn
      - sshpass
      - terminator
      - variety
    state: present
