---
- name: software | snap | install multipass package
  tags: multipass
  become: yes
  become_method: sudo
  snap:
    name:
      - multipass
      - ubuntu-cloud-image
  when:
    - multipass is defined
    - multipass

