---
#
# See install doc: https://protonvpn.com/support/linux-ubuntu-vpn-setup/
#
- name: software | protonvpn block
  block:
    - name: software | protonvpn | add protonvpn to apt cache
      apt:
        deb: https://protonvpn.com/download/protonvpn-stable-release_{{ protonvpn_version }}.deb

    - name: software | protonvpn | update apt cache if older 1 hour
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: software | protonvpn | install protonvpn and prerequisites
      apt:
        pkg:
          - protonvpn
          - gnome-shell-extension-appindicator
          - gir1.2-appindicator3-0.1
        state: present

    - name: software | protonvpn | select display-manager
      become: true
      become_method: sudo
      debconf:
        name: gnome-shell-extension-appindicator
        question: shared/default-x-display-manager
        value: lightdm
        vtype: select

    - name: software | protonvpn | confirm display-manager
      become: true
      become_method: sudo
      debconf:
        name: gnome-shell-extension-appindicator
        question: shared/default-x-display-manager
        value: true
        vtype: boolean

  when:
    - protonvpn is defined
    - protonvpn
