---
#
# See install doc: https://protonvpn.com/support/linux-ubuntu-vpn-setup/
#
- name: Software | protonvpn block
  when:
    - protonvpn is defined
    - protonvpn
  block:
    - name: Software | protonvpn | add protonvpn to apt cache
      apt:
        deb: https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_{{ protonvpn_version }}.deb

    - name: Software | protonvpn | install protonvpn and prerequisites
      apt:
        update_cache: true
        pkg:
          - protonvpn
          - gnome-shell-extension-appindicator
          - gir1.2-appindicator3-0.1
        state: present

    - name: Software | protonvpn | select display-manager
      become: true
      become_method: sudo
      debconf:
        name: gnome-shell-extension-appindicator
        question: shared/default-x-display-manager
        value: lightdm
        vtype: select

    - name: Software | protonvpn | confirm display-manager
      become: true
      become_method: sudo
      debconf:
        name: gnome-shell-extension-appindicator
        question: shared/default-x-display-manager
        value: true
        vtype: boolean
