---
- name: Software | snap | install snap packages
  become: true
  become_method: sudo
  snap:
    name:
      - bpytop
      - digikam
      - lxd
      - docfetcher
      - remarkable
      - ssh-audit

- name: Software | snap connect | allow access to NAS
  become: true
  become_method: sudo
  ansible.builtin.shell: 'snap connect {{ item.app }}:{{ item.plug }}'
  args:
    executable: /bin/bash
  register: connect_result
  with_items:
    - { app: 'digikam', plug: 'removable-media' }
    - { app: 'docfetcher', plug: 'removable-media' }
    - { app: 'remarkable', plug: 'removable-media' }
  changed_when: connect_result.rc == 0
