---
- name: software | snap | install snap packages
  become: true
  become_method: sudo
  snap:
    name:
      - digikam
      - keepassxc
      - lxd
      - htop
      - docfetcher
      - signal-desktop
      - ssh-audit
      - android-file-transfer-linux

- name: software | snap connect | allow access to NAS
  become: true
  become_method: sudo
  command: 'snap connect {{ item.app }}:{{ item.plug }}'
  register: connect_result
  with_items:
    - { app: 'digikam', plug: 'removable-media' }
    - { app: 'keepassxc', plug: 'removable-media' }
    - { app: 'docfetcher', plug: 'removable-media' }
  changed_when: connect_result.rc == 0
