---
- name: software | steam block
  block:
    - name: software | steam | install package
      tags: steam,steam
      apt:
        state: present
        name: steam

    - name: software | steam | install steam-devices package
      tags: steam,steam
      apt:
        state: present
        name: steam-devices

    - name: install vulkan drivers
      tags: drivers,steam
      apt:
        state: present
        pkg:
          - mesa-vulkan-drivers
          - libvulkan1
          - vulkan-tools
  when:
    - steam is defined
    - steam
