---
- name: Software | steam block
  when:
    - steam is defined
    - steam
  block:
    - name: Software | steam | install package
      ansible.builtin.apt:
        state: present
        name: steam

    - name: Software | steam | install steam-devices package
      ansible.builtin.apt:
        state: present
        name: steam-devices

    - name: Install vulkan drivers
      ansible.builtin.apt:
        state: present
        pkg:
          - mesa-vulkan-drivers
          - libvulkan1
          - vulkan-tools
