---
- name: software | steam | install package
  tags: steam,steam
  apt:
    state: present
    name: steam
  when:
    - steam is defined
    - steam == "yes"

- name: software | steam | install steam-devices package
  tags: steam,steam
  apt:
    state: present
    name: steam-devices
  when:
    - steam is defined
    - steam == "yes"

- name: install vulkan drivers
  tags: drivers,steam
  apt:
    state: present
    pkg:
      - mesa-vulkan-drivers
      - libvulkan1
      - vulkan-utils
  when:
    - steam is defined
    - steam == "yes"
