---
- name: software | terminator block
  block:
    - name: software | terminator | create config directory
      tags: software,packages
      file:
        path: /home/bernhard/{{ item.dir }}
        state: directory
        owner: bernhard
        group: users
        mode: 0700
      with_items:
        - { dir: '.config/terminator' }

    - name: software | install terminator
      tags: software,packages
      apt:
        pkg:
          - terminator
        state: present

    - name: software | terminator | copy config file
      copy:
        src: users/bernhard/{{ item.src }}
        dest: /home/bernhard/{{ item.dest }}
        owner: bernhard
        group: users
        mode: 0600
      with_items:
        - { src: 'terminator_config', dest: '.config/terminator/config' }

    - name: software | terminator | copy desktop file
      become: yes
      become_method: sudo
      copy:
        src: users/bernhard/{{ item.src }}
        dest: /usr/share/applications/{{ item.dest }}
        owner: bernhard
        group: users
        mode: 0600
      with_items:
        - { src: 'terminator_desktop', dest: 'terminator.desktop' }
  when:
    - terminator is defined
    - terminator

