---
- name: software | vagrant block
  block:
    - name: software | vagrant | update repositories and install vagrant
      apt:
        name: vagrant
        update_cache: true

    - name: software | vagrant | add group to user bernhard
      become: yes
      become_method: sudo
      user:
        name: bernhard
        groups: vagrant
        append: yes
  when:
    - vagrant is defined
    - vagrant

