---
- name: software | vagrant | add apt signing key
  apt_key:
    file: https://apt.releases.hashicorp.com/gpg
    state: present
  when:
    - vagrant is defined
    - vagrant == "yes"

- name: software | vagrant | add hashicorp apt repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present
  when:
    - vagrant is defined
    - vagrant == "yes"

- name: softwre | vagrant | update repositories and install vagrant
  apt:
    name: vagrant
    update_cache: true
  when:
    - vagrant is defined
    - vagrant == "yes"
