---
- name: software | vagrant block
  tags: vagrant
  block:
#
# Display keyid: curl -fsSL  https://apt.releases.hashicorp.com/gpg | tee vagrant.asc | gpg --keyid-format long
# id: E8A032E094D8EB4EA189D270DA418C88A3219F7B
#
    - name: software | vagrant | add vagrant apt key to keyring file
      apt_key:
        id: E8A032E094D8EB4EA189D270DA418C88A3219F7B
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /etc/apt/trusted.gpg.d/vagrant.gpg

    - name: software | vagrant | add vagrant apt repository
      apt_repository:
        filename: vagrant
        repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main'
        state: present
        update_cache: yes

    - name: software | vagrant | update repo and install vagrant & dependencies
      apt:
        pkg:
          - vagrant
          - vagrant-libvirt
          - ebtables
          - dnsmasq-base
          - libxslt-dev
          - libxml2-dev
          - libvirt-dev
          - zlib1g-dev
          - ruby-dev
          - ruby-libvirt
        state: present
        update_cache: true

    - name: Remove old plugin directory
      file:
        path: /mnt/Data/vagrant
        state: absent

  become: yes
  become_method: sudo
  when:
    - vagrant is defined
    - vagrant

