---
- name: software | vagrant block
  tags: vagrant
  block:
#
# apt-key is deprecated - use curl to get the gpg key and write it to /usr/share/keyrings directory
#
    - name: software | vagrant | add vagrant apt key to keyring file
      shell: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | \
        gpg --dearmor | \
        sudo tee /usr/share/keyrings/vagrant.gpg > /dev/null

    - name: software | vagrant | add vagrant apt repository
      apt_repository:
        filename: vagrant
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/vagrant.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main'
        state: present
        update_cache: yes

    - name: software | vagrant | update repo and install vagrant & dependencies
      apt:
        pkg:
          - vagrant
          - vagrant-libvirt
          - ebtables
          - dnsmasq-base
          - libxslt-dev
          - libxml2-dev
          - libvirt-dev
          - zlib1g-dev
        state: present
        update_cache: true

    - name: Remove old plugin directory
      file:
        path: /mnt/Data/vagrant
        state: absent

  become: yes
  become_method: sudo
  when:
    - vagrant is defined
    - vagrant
