---
- name: software | vagrant block
  block:
    - name: add apt key
      shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
   
    - name: software | vagrant | add repository into sources list
      apt_repository:
        repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main'
        state: present
  
    - name: software | vagrant | update repositories and install vagrant
      apt:
        name: vagrant
        update_cache: true

  when:
    - vagrant is defined
    - vagrant

