---
- name: software | variety block
  block:
    - name: software | variety | install variety
      tags: variety
      apt:
        name: variety
        state: present

    - name: software | terminator | create config directory
      tags: software,packages
      file:
        path: /home/bernhard/{{ item.dir }}
        state: directory
        owner: bernhard
        group: users
        mode: 0740
      with_items:
        - { dir: '.config/variety' }


    - name: software | variety | copy variety.conf file
      tags: dotfiles,dotfiles-bernhard
      copy:
        src: users/bernhard/variety_config
        dest: /home/bernhard/.config/variety/variety.conf
        owner: bernhard
        group: users

  when:
    - variety is defined
    - variety

