---
- name: software | variety block
  block:
    - name: software | variety | install variety
      tags: variety
      apt:
        name: variety
        state: present

    - name: software | terminator | create config directory
      tags: software,packages
      file:
        path: /home/bernhard/{{ item.dir }}
        state: directory
        owner: bernhard
        group: users
        mode: 0740
      with_items:
        - { dir: '.config/variety' }


    - name: software | variety | copy variety.conf file
      tags: dotfiles,dotfiles-bernhard
      copy:
        src: /usr/share/variety/config/variety.conf
        dest: /home/bernhard/.config/variety/variety.conf
        owner: bernhard
        group: users
        mode: 0644

    - name: Replace all installed sources
      replace:
        path: /home/bernhard/test/variety.conf
        regexp: "{{ item.regex }}"
        replace: "{{ item.repl }}"
      with_items:
        - { regex: '^src1 = True', repl: 'src1 = False' }
        - { regex: '^src2 = True', repl: 'src2 = False' }
        - { regex: '^src3 = True', repl: 'src3 = False' }
        - { regex: '^src4 = True', repl: 'src4 = False' }
        - { regex: '^src5 = True', repl: 'src5 = False' }
        - { regex: '^src11 = True', repl: 'src11 = False' }
#
# If there are more than one matches in the file, ansible lineinfile
# would replace only the last line matched or found,
# or insertafter the last matched line
#
    - name: Insert background line
      lineinfile:
        path: /home/bernhard/test/variety.conf
        regexp: '^src\d.'
        insertafter: '^src'
        line: 'src12 = True|folder|/mnt/NAS/media/Pictures/Weltreise'

  when:
    - variety is defined
    - variety

