 #=============================================================
#
# PERSONAL $HOME/.bashrc FILE for bash-3.0 (or later)
# By Emmanuel Rouat <no-email>
#
# Last modified: Sun Nov 30 16:27:45 CET 2008
# This file is read (normally) by interactive shells only.
# Here is the place to define your aliases, functions and
# other interactive features like your prompt.
#
# The majority of the code here assumes you are on a GNU 
# system (most likely a Linux box) and is based on code found
# on Usenet or internet. See for instance:
#
# http://tldp.org/LDP/abs/html/index.html
# http://www.caliban.org/bash/
# http://www.shelldorado.com/scripts/categories.html
# http://www.dotfiles.org/
#
# This bashrc file is a bit overcrowded -- remember it is just
# just an example. Tailor it to your needs.
#
#
#=============================================================

#----------------- debugging ---------------------
# uncomment the following lines for debugging
#export PS4='xtrace $0 line $LINENO -> '
#set -o nounset 	# Useful for debugging
#set -o xtrace          # Useful for debugging.
#----------------- debugging ---------------------

#-------------------------------------------------------------
# Source global definitions (if any)
#-------------------------------------------------------------

[ -z "$PS1" ] && return		# if not running interactively, return

if [ -f /etc/bashrc ]; then
        . /etc/bashrc  		# --> Read /etc/bashrc, if present.
fi

#-------------------------------------------------------------
# You may want to put all your alias definitions into a separate
# file like ~/.bash_aliases, instead of adding them here directly.
#-------------------------------------------------------------

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases		# --> Read /$HOME/.bash_aliases if present
fi

#-------------------------------------------------------------
# Temporary fix for Tilix terminal (hopefully)
#-------------------------------------------------------------

#if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
#        source /etc/profile.d/vte.sh
#fi

#---------------------------------------------------------------------
# use the ~/.dircolors as input to dircolors command which will
# create the LS_COLORS variable and exports it.
# see https://github.com/seebi/dircolors-solarized/raw/master/dircolors.256dark
# for a sample.
#---------------------------------------------------------------------

eval `dircolors -b ~/.dircolors`

#-------------------------------------------------------------
# Some settings
#-------------------------------------------------------------

ulimit -S -c 0          # Don't want any coredumps.
set -o notify
set -o noclobber
set -o ignoreeof
set -o nounset

export HOSTFILE=$HOME/.hosts    # Put list of remote hosts in ~/.hosts ...

# optimize bash_history ($HISTFILE)
# ignore duplicate lines in the history.
# ignore commands that  start with space `ignorespace'.
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=2000
export HISTFILESIZE=8000
export HISTIGNORE="free*:exit:clear:man*:mkdir*:rm*:mv*"
export HISTTIMEFORMAT="%F %T: "	# Date, Time
shopt -s histappend
shopt -s histverify
shopt -s autocd
shopt -s cdspell
shopt -s dotglob
shopt -s interactive_comments # default

export ENV=$HOME/.bashrc
export EDITOR=vim
export VISUAL=vim
export NO_AT_BRIDGE=1	# to avoid dbind-warning messages with gedit

export HOST=`hostname -s`
export TERM=xterm-256color

export PATH_TO_FX=/opt/javafx-sdk-17.0.1/lib
export CLASSPATH=.:/usr/lib/jvm/java-17-openjdk-amd64/lib:$PATH_TO_FX

# $HOME/bin is added to PATH in .profile, so not required in .bashrc
#if [ -d "$HOME/bin" ] ; then
#    PATH="$HOME/bin:$PATH"
#fi

export -n SESSION_MANAGER   # required for Digikam
export VAGRANT_HOME=/mnt/Data/vagrant
export KUBECONFIG=~/.kube/config

#-------------------------------------------------------------
# Color definitions, less definitions
#-------------------------------------------------------------

# Normal Colors
black=$'\e[38;5;16m'
red=$'\e[38;5;160m'
green=$'\e[38;5;46m'
yellow=$'\e[38;5;11m'
blue=$'\e[38;5;26m'
purple=$'\e[38;5;211m'
cyan=$'\e[38;5;45m'
white=$'\e[0;37m'
magenta=$'\e[38;5;165m'

WHITE=$'\e[1;37m'
BOLD=$"$(tput bold)"
NC=$'\e[0m'             # Color reset

# To use bold colors prefix with BOLD variable

# Background
on_black=$'\e[48;5;16m'       # Black
on_red=$'\e[48;5;196m'        # Red
on_green=$'\e[48;5;46m'       # Green
on_yellow=$'\e[48;5;226m'     # Yellow
on_blue=$'\e[48;5;43m'        # Blue
on_purple=$'\e[48;5;45m'      # Purple
on_cyan=$'\e[48;5;45m'        # Cyan
on_white=$'\e[48;5;255m'      # White
on_magenta=$'\e[48;5;201m' 	  # Magenta

ALERT=${WHITE}${on_red}   # Bold White on red background

# echo -e "${cyan}This is BASH: ${yellow}${BASH_VERSION%%[^0-9.]*}${cyan}\
# - System: ${yellow}`uname -sr`${cyan} `unity --version`${NC}"

#---------------------------------------------------------------------
# Replace the initial Title with the text in every xterm
#---------------------------------------------------------------------

SYS=`uname -r`
EXTIP=`curl -4 ifconfig.so`

case "$TERM" in
  xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\e]0;${USER}@${HOSTNAME} - ${SYS} on ${EXTIP}\a"'
#	PROMPT_COMMAND='echo -ne "${yellow}${USER}@${HOSTNAME}: : ${PWD/$HOME/~}\a"'
    ;;
  *)
    ;;
esac

#-------------------------------------------------------------
# Shell Prompt for differenct users
# emoji copied from https://emojipedia.org  ⛷️    🌡️  🧭  🎁
#-------------------------------------------------------------

case ${USER} in
  bernhard|marlies)
    export PS1='\n\[$black $on_magenta\][\D{%F %T}]\[$black $on_yellow\][\u on \h]\[$black $on_red\][$PWD]$NC\n\[$cyan\]😄==\$ \[$NC'
    export PS2='\[$cyan\]😄==\$ \[$NC'
  ;;
  ubuntu)
    export PS1='\n\[$black $on_magenta\][🔥LXD]\[$black $on_yellow\][\u on \h]\[$black $on_green\][$PWD]$NC\n\[$cyan\]🔥==\$ \[$NC'
    export PS2='\[$cyan\]🔥==\$ \[$NC'
  ;;
  root)
    export PS1='\n\[$black $on_yellow\][\u on \h]\[$black $on_red\][$PWD]$NC\n\[$red\]⚠️ ‼️ ==\> \[$NC'
  ;;
  *)
    export PS1='\n‼️\[$black $on_magenta\][\u]\[$black $on_yellow\][\s \v] => \[$NC'
  ;;
esac

#-------------------------------------------------------------
# tailoring 'less'
#-------------------------------------------------------------

unset -v LESSCHARSET # Fix manpages looking funky
export PAGER=less    #less

export LESS_TERMCAP_mb=$'\e[00;38;5;196m' # red, begin blinking
export LESS_TERMCAP_md=$'\e[00;38;5;226m' # yellow, begin bold
export LESS_TERMCAP_me=$'\e[0m'           # end mode
export LESS_TERMCAP_se=$'\e[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\e[38;5;11m\e[48;5;33m'
#					  # begin standout-mode - info box
#					  # yellow on blue
export LESS_TERMCAP_ue=$'\e[0m'           # end underline
export LESS_TERMCAP_us=$'\e[04;38;5;164m' # begin underline

#--------------------------------------------------------------------
# lesspipe is considered a dangerous feature of "less" - don't use it
#--------------------------------------------------------------------
#export LESSOPEN='|/usr/bin/lesspipe %s 2>&-'
#
# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# Use this if lesspipe (link to *.sh) exists
#export LESS='-i -N -w  -z-4 -g -e -M -X -F -R -P%t?f%f \
#:stdin .?pb%pb\%:?lbLine %lb:?bbByte %bb:-...'

#export LESS='-iMnQRSw -PM[%i/%m\: ?f%f:STDIN.] [C\:%c] \
#[L\:?l%l:*.-?lb%lb:*./?L%L:*.] [P\:?d%d:*./?D%D:*.] \
#[O\:?b%b:*./?B%B:*.] [?pt%pt:*.-?Pb%Pb:*.\%]'
#
# end of lesspipe statements
#
#-------------------------------------------------------------
# Import functions: --> Read /$HOME/.bash_functions if present
#-------------------------------------------------------------

if [ -f ~/.bash_functions ]; then
    . ~/.bash_functions
fi

#--------------------------------------------------------------
# end of .bashrc
#--------------------------------------------------------------

