---
#
#  install info from: https://computingforgeeks.com/install-kvm-centos-rhel-ubuntu-debian-sles-arch/
#
- name: Software | kvm, qemu, libvirt block
  when:
    - kvm is defined
    - kvm
  block:
    - name: Software | kvm | install cpu-checker prerequisite
      apt:
        name: cpu-checker

    - name: Software | kvm | check system for kvm
      command: kvm-ok
      register: kvm_result
      changed_when: "'KVM acceleration can be used' in kvm_result.stdout"

    - name: Software | kvm | install kvm and dependencies
      apt:
        pkg:
          - qemu-kvm
          - libvirt-dev
          - libvirt-daemon
          - libvirt-daemon-system
          - libvirt-clients
          - virtinst
          - virt-manager
          - virt-viewer
          - bridge-utils
          - libosinfo-bin
          - libguestfs-tools
        state: present
      when:
        - "'KVM acceleration can be used' in kvm_result.stdout"

    - name: Insert vhost-net in /etc/modules
      become_method: sudo
      become: yes
      lineinfile:
        dest: /etc/modules
        line: 'vhost-net'

    - name: Software | kvm | add groups libvirt, kvm to user bernhard
      become: yes
      become_method: sudo
      user:
        name: bernhard
        groups: libvirt,kvm
        append: yes
      when:
        - "'KVM acceleration can be used' in kvm_result.stdout"

    - name: Software | kvm | create config/libvirt directory
      file:
        path: /home/bernhard/{{ item.dir }}
        state: directory
        owner: bernhard
        group: users
        mode: 0740
      with_items:
        - { dir: '.config/libvirt' }

    - name: Software | kvm | copy libvirt config file
      copy:
        src: /etc/libvirt/{{ item.src }}
        dest: /home/bernhard/{{ item.dest }}
        owner: bernhard
        group: users
        mode: 0640
      with_items:
        - { src: 'libvirt.conf', dest: '.config/libvirt/libvirt.conf' }

    - name: Software | kvm | remove hash from uri_default line
      replace:
        path: /home/bernhard/.config/libvirt/libvirt.conf
        regexp: "{{ item.regexp }}"
        replace: "{{ item.value }}"
      with_items:
        - { regexp: '#uri_default', value: 'uri_default' }

    - name: Software | kvm | insert log-filter line
      lineinfile:
        path: /etc/libvirt/libvirtd.conf
        insertafter: '^#log_filters='
        line: 'log_filters="1:qemu"'

    - name: Software | kvm | insert log-output line
      lineinfile:
        path: /etc/libvirt/libvirtd.conf
        insertafter: '^#log_output='
        line: 'log_filters="1:file:/var/log/libvirt/libvirtd.log"'
