---
#
# external location for instances, check: https://canonical.com/multipass/docs/configure-multipass-storage
#
- name: Software | multipass block
  become: true
  become_method: ansible.builtin.sudo
  when:
    - multipass is defined
    - multipass
  block:
    - name: Softeare | multipass | Recursively remove directory /mnt/Storage/multipass
      ansible.builtin.file:
        path: /mnt/Storage/multipass
        state: absent

    - name: Software | snap | install multipass package
      community.general.snap:
        name:
          - multipass

    - name: Software | multipass | stop multipass daemon
      ansible.builtin.shell: snap stop multipass
      args:
        executable: /bin/bash
      register: snap_stop
      changed_when: snap_stop.rc == 0

    - name: Software | multipass | connect multipass:removable-media for /mnt odr /media
      ansible.builtin.shell: snap connect multipass:removable-media
      args:
        executable: /bin/zsh
      register: snap_removable
      changed_when: snap_removable.rc == 0

    - name: Software | multipass | connect multipass:all-home for /home
      ansible.builtin.shell: snap connect multipass:all-home
      args:
        executable: /bin/bash
      register: snap_home
      changed_when: snap_home.rc == 0

    - name: Software | multipass | Create target directory /mnt/Storage/multipass
      ansible.builtin.file:
        path: /mnt/Storage/multipass
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Software | multipass | Create directory for override.conf
      ansible.builtin.file:
        path: "/etc/systemd/system/snap.multipass.multipassd.service.d"
        state: directory
        owner: root
        group: root
        mode: "0744"

    - name: Software | multipass | Create override.conf file with path entry
      ansible.builtin.copy:
        dest: "/etc/systemd/system/snap.multipass.multipassd.service.d/override.conf"
        content: |
          [Service]
          Environment=MULTIPASS_STORAGE=/mnt/Storage/multipass
          TimeoutStopSec=60
        owner: root
        group: root
        mode: "0644"

    - name: Software | multipass | reload daemon - must be before removing data directories
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Software | multipass | start multipass
      ansible.builtin.shell: "{{ item }}"
      with_items:
        - "snap start multipass"
      args:
        executable: /bin/bash
      register: start_daemon
      changed_when: start_multipass.rc == 0

    - name: Softeare | multipass | Recursively remove original data directories
      ansible.builtin.file:
        path: /var/snap/multipass/common/{{ item.dir }}
        state: absent
      with_items:
        - { dir: data/multipassd }
        - { dir: cache/multipassd }
