---
- name: software | vagrant block
  tags: vagrant
  block:
#
# apt-key is deprecated - use curl to get the gpg key and write it to /usr/share/keyrings directory
#
    - name: software | vagrant | add vagrant apt key to keyring file
      shell: |
        set -o pipefail
        curl -fsSL https://apt.releases.hashicorp.com/gpg | \
        gpg --dearmor | \
        sudo tee /usr/share/keyrings/vagrant.gpg > /dev/null
      args:
        executable: /bin/bash
      register: vagrant_gpgkey
      changed_when: vagrant_gpgkey.rc == 0

    - name: software | vagrant | add vagrant apt_repository, filename creates vagrant.list in /etc/apt/sources.list.d
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/vagrant.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main'
        filename: vagrant
        state: present
        update_cache: true

    - name: software | vagrant | update repo and install vagrant & dependencies
      apt:
        pkg:
          - vagrant
          - ebtables
          - dnsmasq-base
          - libvirt-daemon-system
          - virt-manager
          - libxslt-dev
          - libxml2-dev
          - libvirt-dev
          - zlib1g-dev
          - ruby-dev
          - libguestfs-tools
        state: present

    - name: software | vagrant | activate all deb-src entries in /etc/apt/sources.list
      shell: |
        set -o pipefail
        cp /etc/apt/sources.list /etc/apt/sources.list~
        sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
      args:
        executable: /bin/bash
      register: debsrc_activate
      changed_when: debsrc_activate.rc == 0

    - name: software | vagrant | remove vagrant-libvirt if present
      apt:
        pkg:
          - vagrant-libvirt
        state: absent

    - name: software | vagrant | set vagrant-libvirt on mark hold
      ansible.builtin.dpkg_selections:
        name: vagrant-libvirt
        selection: hold

    - name: software | vagrant | build dependencies
      apt:
        pkg:
          - vagrant
          - ruby-libvirt
        state: build-dep

    - name: software | vagrant | install vagrant-libvirt plugin
      shell: |
        set -o pipefail
        vagrant plugin install vagrant-libvirt
      args:
        executable: /bin/bash
      register: libvirt_plugin
      changed_when: libvirt_plugin.rc == 0

    - name: software | vagrant | remove boxes and system entries
      file:
        path: /mnt/Data/vagrant
        state: absent

  become: yes
  become_method: sudo
  when:
    - vagrant is defined
    - vagrant
