---
- name: Software | vagrant block
  become: true
  become_method: sudo
  when:
    - vagrant is defined
    - vagrant
  block:

    #- name: Software | vagrant | add blacklist file due to hypervisor error
    #  ansible.builtin.copy:
    #    src: etc/{{ item.src }}
    #    dest: /etc/{{ item.dest }}
    #    owner: root
    #    group: root
    #    mode: 0644
    #  with_items:
    #    - { src: 'blacklist-kvm.conf', dest: 'modprobe.d/blacklist-kvm.conf' }

    #
    # apt-key is deprecated - use curl to get the gpg key and write it to /etc/apt/trusted.gpg.d directory
    #
    - name: Software | vagrant | add vagrant apt key to keyring file
      ansible.builtin.shell: |
        set -o pipefail
        curl -fsSL https://apt.releases.hashicorp.com/gpg | \
        gpg --dearmor | \
        sudo tee /etc/apt/trusted.gpg.d/vagrant.gpg > /dev/null
      args:
        executable: /bin/bash
      register: vagrant_gpgkey
      changed_when: vagrant_gpgkey.rc == 0

    - name: Software | vagrant | add vagrant apt_repository, filename creates vagrant.list in /etc/apt/sources.list.d
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/vagrant.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main'
        filename: vagrant
        state: present
        update_cache: true

    - name: Software | vagrant | update repo and install vagrant & dependencies
      ansible.builtin.apt:
        pkg:
          - vagrant
          - ebtables
          - dnsmasq-base
          - libvirt-daemon-system
          - virt-manager
          - libxslt-dev
          - libxml2-dev
          - libvirt-dev
          - zlib1g-dev
          - ruby-dev
          - libguestfs-tools
        state: present

    - name: Software | vagrant | activate all deb-src entries in /etc/apt/sources.list
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: '^# deb-src'
        replace: 'deb-src'

    - name: Software | vagrant | enable deb-src for plugin installation
      ansible.builtin.replace:
        path: /etc/apt/sources.list.d/ubuntubudgie-ubuntu-backports-{{ ansible_distribution_release }}.list
        regexp: '^# deb-src'
        replace: 'deb-src'

    - name: Software | vagrant | remove vagrant-libvirt if present
      ansible.builtin.apt:
        pkg:
          - vagrant-libvirt
        state: absent

    - name: Software | vagrant | set vagrant-libvirt on mark hold
      ansible.builtin.dpkg_selections:
        name: vagrant-libvirt
        selection: hold

    - name: Software | vagrant | build dependencies
      ansible.builtin.apt:
        pkg:
          - vagrant
          - ruby-libvirt
        state: build-dep

    - name: Software | vagrant | install vagrant-libvirt plugin
      ansible.builtin.shell: |
        set -o pipefail
        vagrant plugin install vagrant-libvirt
      args:
        executable: /bin/bash
      register: libvirt_plugin
      changed_when: libvirt_plugin.rc == 0

    - name: Software | vagrant | remove boxes and system entries
      ansible.builtin.file:
        path: /mnt/Data/vagrant
        state: absent
