---
#
# VirtualBox V7.0.8:    https://download.virtualbox.org/virtualbox/7.0.8/virtualbox-7.0_7.0.8-156879~Ubuntu~jammy_amd64.deb
# VirtualBox Extension: https://download.virtualbox.org/virtualbox/7.0.8/Oracle_VM_VirtualBox_Extension_Pack-7.0.8.vbox-extpack
#
- name: Software | virtualbox block
  become: true
  become_method: sudo
  when:
    - virtualbox is defined
    - virtualbox
  block:
  
    - name: Software | virtualbox | set fact data set names
      ansible.builtin.set_fact:
        vbox_ext: "Oracle_VM_VirtualBox_Extension_Pack-7.0.8.vbox-extpack"
        vbox_deb: "virtualbox-7.0_7.0.8-156879~Ubuntu~jammy_amd64.deb"
 
    - name: Software | virtualbox | install virtualbox deb package
      ansible.builtin.apt:
        deb: https://download.virtualbox.org/virtualbox/7.0.8/{{ vbox_deb }}

    - name: Software | virtualbox | download virtualbox extension package
      ansible.legacy.shell: |
        set -o pipefail
        wget -P /tmp -q --show-progress --https-only --timestamping \
              https://download.virtualbox.org/virtualbox/7.0.8/{{ vbox_ext }}
      args:
        executable: /bin/bash
      register: vbox_extpack
      changed_when: vbox_extpack.rc == 0

    - name: Software | virtualbox | install extension pack
      ansible.legacy.shell: |
        set -o pipefail
        vboxmanage extpack install --replace --accept-license=sh256  /tmp/{{ vbox_ext }}
      args:
        executable: /bin/bash
      register: install_extpack
      changed_when: install_extpack.rc == 0

    - name: Software | virtualbox | add vboxusers group to user bernhard
      user:
        name: bernhard
        groups: vboxusers
        append: yes
    
    - name: Software | virtualbox | change location for VirtualBox VMs
      ansible.legacy.shell: |
        set -o pipefail
        vboxmanage setproperty machinefolder /mnt/Storage/VirtualBox
      args:
        executable: /bin/bash
      register: vm_location
      changed_when: vm_location.rc == 0
