---
bernhard_passwd: $y$j9T$P3bd9n4L/uH3vWqPvQ0De1$0tByDGM00LbfjYNTzK3ktt6F.vLcedz66izhWQmAM1A
ansible_passwd: $y$j9T$iUenE9kyccSKeW92NPKqK0$y1TRK7DGD4HUNdAPyUtGADFZzTw.oQr7hb3Thkqg1i1
ubuntu_passwd: $y$j9T$dBtjA9x1ZvaXrkR3ipV1P.$iClKesJVwialgHusRqKI4Uku3ZJtgVy4T94lX4LdIE3
