---
- name: Gnome | desktop block
  become: true
  become_method: sudo
  block:
    - name: Gnome | desktop | copy wallpaper file
      ansible.builtin.copy:
        src: images/{{ item }}
        dest: /home/{{ user_name }}/.local/share/backgrounds
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        mode: 0644
      with_items:
        - saturn-wallpaper.jpg
        - jupiter.jpg
        - cygnus-x1.jpg

    - name: Gnome | desktop | set wallpaper
      community.general.dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///home/{{ user_name }}/.local/share/backgrounds/saturn-wallpaper.jpg'"

    - name: Gnome | desktop | disable touchpad
      community.general.dconf:
        key: "/org/gnome/desktop/peripherals/touchpad/{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: 'send-events', value: "'disabled'" }

    - name: Gnome | desktop | set interface values
      community.general.dconf:
        key: "/org/gnome/desktop/interface/{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: 'color-scheme', value: "'prefer-dark'" }
        - { key: 'cursor-size', value: '48' }
        - { key: 'cursor-theme', value: "'DMZ-Black'" }
        - { key: 'document-font-name', value: "'Noto Sans 13'" }
        - { key: 'font-name', value: "'Noto Sans 13'" }
        - { key: 'gtk-theme', value: "'QogirBudgie-dark'" }
        - { key: 'icon-theme', value: "'Humanity-Dark'" }
        - { key: 'monospace-font-name', value: "'Noto Mono Bold 13'" }
        - { key: 'text-scaling-factor', value: '1.10' }

    - name: Gnome | gedit | set editor values
      community.general.dconf:
        key: "/org/gnome/gedit/preferences/editor/{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: 'scheme', value: "'cobalt'" }
        - { key: 'tabs-size', value: 'uint32 4' }
