---
- name: Software | brave browser block
  become: true
  become_method: ansible.builtin.sudo
  block:
    #
    # apt-key is deprecated - use curl to get the gpg key and write it to /usr/share/keyrings directory
    #
    - name: Software | brave browser | add brave gpg key to keyring file
      ansible.legacy.shell: |
        set -o pipefail
        curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
#        gpg --dearmor | \
#        tee /etc/apt/trusted.gpg.d/brave-browser-archive-keyring.gpg > /dev/null
      args:
        executable: /bin/bash
      register: brave_gpgkey
      changed_when: brave_gpgkey.rc == 0

    - name: Software | brave browser | add brave apt repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main'
        state: present

    - name: Software | brave browser | install brave & prerequisite
      ansible.builtin.apt:
        update_cache: true
        name:
          - gnupg2
          - brave-browser

 
