---
- name: btop block
  block:
    - name: system_setup | btop++ | download latest release info
      ansible.legacy.shell: |
        set -o pipefail
        curl --silent "https://api.github.com/repos/aristocratos/btop/releases/latest" |
        jq -r .tag_name
      args:
        executable: /bin/bash
      register: btop_release
      changed_when: btop_release.rc == 0

    - name: system_setup | btop++ | display latest release
      debug:
        var: btop_release.stdout
        verbosity: 2

    - name: system_setup | btop++ | display source line for download
      debug:
        msg: "https://github.com/aristocratos/btop/releases/download/{{ btop_release.stdout }}/btop-x86_64-linux-musl.tbz"
        verbosity: 2

    - name: system_setup | btop++ | install latest btop++ binary
      ansible.builtin.unarchive:
        src: https://github.com/aristocratos/btop/releases/download/{{ btop_release.stdout }}/btop-x86_64-linux-musl.tbz
        dest: /tmp
        remote_src: yes
        owner: root
        group: root
        mode: 0755

    - name: system_setup | btop++ | copy unarchived btop module to /usr/local/bin
      copy:
        src: /tmp/btop/bin/btop
        dest: /usr/local/bin
        owner: root
        group: root
        mode: 0755

  become: true
  become_method: sudo
