---
- name: Software | clamav | install clamav and security packages
  ansible.builtin.apt:
    state: present
    pkg:
      - gufw
      - clamav
      - chkrootkit
      - bleachbit

- name: Software | clamav | create system group clamav
  ansible.builtin.group:
    name: clamav
    state: present
    system: true

- name: Software | clamav | create system user clamav
  ansible.builtin.user:
    name: clamav
    comment: "Clam Antivirus"
    create_home: false
    shell: /bin/false
    group: clamav
    system: true

- name: Software | clamav | create clamav directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: /var/log/clamav
    state: directory
    owner: clamav
    group: clamav
    mode: "0774"

- name: Software | clamav | adding existing user to group clamav (logoff, logon required) '{{ user_name }}'
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: clamav
    append: true

- name: Software | clamav | Creating clamscan file for logrotate
  ansible.builtin.copy:
    dest: /etc/logrotate.d/clamscan
    content: |
      /var/log/clamav/clamscan.log {
        rotate 4
        daily
        compress
        missingok
        notifempty
        create 0660 clamav clamav
      }
    owner: root
    group: root
    mode: "0644"

- name: Software | clamav | systemd service, timer and slice
  ansible.builtin.copy:
    src: file/systemd/{{ item }}
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - clamscan.service
    - clamscan.timer
    - clamscan-cpulimit.slice

- name: Software | clamav | systemd clam service, timer and slice and installed clamav-freshclam.service
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
    daemon_reload: true
#  environment:
#    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"
  with_items:
    - clamscan.timer
    - clamscan-cpulimit.slice
    - clamav-freshclam.service
...
