---
- name: Software | clamav | install clamav and security packages
  ansible.builtin.apt:
    state: present
    pkg:
      - gufw
      - clamav
      - clamav-daemon
      - chkrootkit
      - bleachbit
      - cpulimit

- name: Software | clamav | create clamav directory
  ansible.builtin.file:
    path: /var/log/clamav
    state: directory
    owner: clamav
    group: clamav
    mode: 0774

- name: Software | clamav | adding existing user to group clamav (logoff, logon required) '{{ user_name }}'
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: clamav
    append: yes

- name: Software | clamav | remove StandardOutput line from systemd files
  ansible.builtin.lineinfile: 
    dest: /lib/systemd/system/{{ item }} 
    state: absent 
    regexp: "^StandardOutput="
  with_items:
    - clamav-daemon.service
    - clamav-freshclam.service
   
- name: Software | clamav | Creating clamscan file for logrotate
  ansible.builtin.copy:
    dest: /etc/logrotate.d/clamscan
    content: |
      /var/log/clamav/clamscan.log {
        rotate 4
        daily
        compress
        missingok
        notifempty
        create 0660 clamav clamav
      }
    owner: root
    group: root
    mode: 0644
    
- name: Software | clamav | cron job clamscan for user {{ user_name }}
  ansible.builtin.cron:
    name: daily_clamsacan
    user: "{{ user_name }}"
    minute: 07
    hour: 13
    job: "/usr/bin/clamscan --exclude-dir=/run/user/bernhard/gvfs --exclude-dir=/home/bernhard/.gvfs --detect-pua -r /home/bernhard --log=/var/log/clamav/clamscan.log"

# clamscan must be running for cpulimit to take effect. Limit cpu usage to 30%
- name: Software | clamav | cron job clamscan limit cpu usage for user {{ user_name }}
  ansible.builtin.cron:
    name: daily_clamsacan_cpulimit
    user: "{{ user_name }}"
    minute: 08
    hour: 13
    job: "cpulimit -e clamscan -l 30"

- name: Software | clamav | cron job for root freshclam
  ansible.builtin.cron:
    name: freshclam_update_dbs
    user: root
    minute: 21
    job: "/usr/bin/freshclam --quiet"
