---
- name: Software | clamav | install clamav and security packages
  ansible.builtin.apt:
    state: present
    pkg:
      - gufw
      - clamav
      - chkrootkit
      - bleachbit

- name: Software | clamav | create clamav directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: /var/log/clamav
    state: directory
    owner: clamav
    group: clamav
    mode: "0774"

- name: Software | clamav | adding existing user to group clamav (logoff, logon required) '{{ user_name }}'
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: clamav
    append: true

- name: Software | clamav | replace StandardOutput=syslog line with target journal
  ansible.builtin.replace: 
    path: /lib/systemd/system/{{ item }} 
    regexp: '^StandardOutput=syslog'
    replace: 'StandardOutput=journal'
  with_items:
    - clamav-daemon.service
    - clamav-freshclam.service
   
- name: Software | clamav | Creating clamscan file for logrotate
  ansible.builtin.copy:
    dest: /etc/logrotate.d/clamscan
    content: |
      /var/log/clamav/clamscan.log {
        rotate 4
        daily
        compress
        missingok
        notifempty
        create 0660 clamav clamav
      }
    owner: root
    group: root
    mode: "0644"

- name: Software | clamav | systemd service, timer and slice  for user {{ user_name }}
  ansible.builtin.copy:
    src: file/systemd/{{ item }}
    dest: /home/{{ user_name }}/.config/systemd/user/{{ item }}
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: "0644"
  with_items:
    - daily-clamscan.service
    - daily-clamscan.timer
    - cpulimited.slice

- name: Software | clamav | systemd clam service, timer and slice for user {{ user_name }}
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
    daemon_reload: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"
  with_items:
    - daily-clamscan.timer
    - cpulimited.slice

- name: Software | clamav | systemd service and timer for root
  ansible.builtin.copy:
    src: file/systemd/{{ item }}
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - freshclam-updatedb.service
    - freshclam-updatedb.timer

- name: Software | clamav | systemd freshclam updatedb service and timer
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
    daemon_reload: true
  with_items:
    - freshclam-updatedb.timer
...
