---
- name: software | firefox block
  block:

    - name: software | firefox | remove snap firefox
      snap:
        name: firefox
        state: absent

    - name: software | firefox | create apt file to avoid reinstall of snap firefox
      copy:
        dest: "/etc/apt/preferences.d/mozilla-firefox"
        owner: root
        group: root
        mode: 0644
        content: |
          Package: *
          Pin: release o=LP-PPA-mozillateam
          Pin-Priority: 1001

    - name: software | firefox | add firefox apt repository
      apt_repository:
        repo: 'ppa:mozillateam/ppa'
        state: present
        filename: firefox
        update_cache: yes

# run "sudo apt-key list" to find the full public gpg key
# use the last 8 characters for the export command

    - name: software | firefox | apt-key deprecated - convert trusted.gpg into a member in /etc/apt/trusted.gpg.d
      ansible.legacy.shell: |
        set -o pipefail
        apt-key export CE49EC21 | \
        gpg --dearmour -o /etc/apt/trusted.gpg.d/firefox.gpg
      args:
        executable: /bin/bash
      register: gpg_convert
      changed_when: gpg_convert.rc == 0

    - name: software | firefox | ensure automatic updates of apt firefox
      copy:
        dest: "/etc/apt/apt.conf.d/51unattended-upgrades-firefox"
        content: |
          Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";
        owner: root
        group: root
        mode: 0644

    - name: software | firefox | update cache and install firefox
      ansible.builtin.apt:
        name: firefox
        update_cache: true

    - name: software | firefox | create private profile bpic
      ansible.legacy.shell: firefox -CreateProfile bpic
      become: true
      become_user: "{{ user_name }}"
      
    - name: software | firefox | start ProfileManager and delete default profile
      ansible.legacy.shell: firefox -ProfileManager
      become: true
      become_user: "{{ user_name }}" 

  become: yes
  become_method: sudo
