---
- name: software | firefox block
  block:

    - name: software | firefox | remove snap firefox
      snap:
        name: firefox
        state: absent

    - name: software | firefox | create apt file to avoid reinstall of snap firefox
      copy:
        dest: "/etc/apt/preferences.d/mozilla-firefox"
        owner: root
        group: root
        mode: 0644
        content: |
          Package: *
          Pin: release o=LP-PPA-mozillateam
          Pin-Priority: 1001

    - name: software | firefox | add firefox apt repository
      apt_repository:
        repo: 'ppa:mozillateam/ppa'
        state: present
        filename: firefox
        update_cache: yes

# run "sudo apt-key list" to find the full public gpg key
# use the last 8 characters for the export command

    - name: software | firefox | apt-key deprecated - convert trusted.gpg into a member in /usr/share/keyrings
      shell: |
        set -o pipefail
        apt-key export CE49EC21 | \
        gpg --dearmour -o /usr/share/keyrings/firefox.gpg
      args:
        executable: /bin/bash
      register: gpg_convert
      changed_when: gpg_convert.rc == 0

    - name: software | firefox | ensure automatic updates of apt firefox
      copy:
        dest: "/etc/apt/apt.conf.d/51unattended-upgrades-firefox"
        owner: root
        group: root
        mode: 0644
        content: |
          Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";

    - name: software | firefox | install firefox
      apt:
        pkg:
          - firefox

    - name: software | firefox | create private profile bpic
      command: firefox -CreateProfile bpic
      
    - name: software | firefox | start ProfileManager and delete default profile
      command: firefox -ProfileManager  

  become: yes
  become_method: sudo
