---

- name: Software | geany | install packages
  ansible.builtin.apt:
    state: present
    pkg:
      - geany
      - geany-plugins


- name: Software |  geany | create .config/geany/colorschemes directories
  ansible.builtin.file:
    path: /home/{{ user_name }}/{{ item.dir }}
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: "0755"
  with_items:
    - { dir: ".config/geany" }
    - { dir: ".config/geany/colorschemes" }
    - { dir: ".config/geany/filedefs" }

- name: Software | geany | download geany colorschemes from github
  become: true
  ansible.builtin.git:
    repo: "https://github.com/geany/geany-themes.git"
    dest: "/tmp/geany-themes"
    force: true
    version: master

- name: Software | geany | copy geany colorschemes to .config/geany/colorschemes
  ansible.posix.synchronize:
    src: /tmp/geany-themes/colorschemes/
    dest: /home/{{ user_name }}/.config/geany/colorschemes/
    archive: true

- name: Software | geany | copy filetypes.yaml
  ansible.builtin.copy:
    src: /usr/share/geany/filedefs/filetypes.yaml
    dest: /home/{{ user_name }}/.config/geany/filedefs/filetypes.yaml
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: "0644"

- name: Software | geany | Replace identifier=identifier with types in filetypes.yaml
  ansible.builtin.replace:
    path: /home/{{ user_name }}/.config/geany/filedefs/filetypes.yaml
    regexp: "^identifier=identifier"
    replace: "identifier=types"

- name: Software | geany | Modify cursor and indent guide values
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.replace:
    path: /usr/share/geany/filedefs/filetypes.common
    regexp: "{{ item.src }}"
    replace: "{{ item.dest }}"
  with_items:
    - { src: "^caret=caret", dest: "caret=0x00ff00;0x0;false;false" }
    - { src: "^caret_width=1", dest: "caret_width=3" }
    - { src: "^indent_guide=indent_guide", dest: "indent_guide=0xDAFB31;0xffffff;false;false" }
