---
- name: Software | keepassxc block
  become: true
  become_method: ansible.builtin.sudo
  when:
    - keepassxc is defined
    - keepassxc
  block:

     # run "sudo apt-key list" to find the full public gpg key
     # use the last 8 characters for the export command

    - name: Software | keepassxc | snap install keepassxc
      community.general.snap:
        name: 
          - keepassxc

    - name: Software | keepassxc | snap connect | allow access to NAS
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.shell: 'snap connect {{ item.app }}:{{ item.plug }}'
      args:
        executable: /bin/bash
      register: connect_result
      with_items:
        - { app: 'keepassxc', plug: 'removable-media' }
