---
- name: Software | keepassxc block
  become: true
  become_method: sudo
  when:
    - keepassxc is defined
    - keepassxc
  block:

     # run "sudo apt-key list" to find the full public gpg key
     # use the last 8 characters for the export command

    - name: Software | keepassxc | apt-key deprecated - convert trusted.gpg into member in tursted.gpg.d
      ansible.legacy.shell: |
        set -o pipefail
        apt-key export 0068FCD6 | \
        gpg --dearmour -o /etc/apt/trusted.gpg.d/keepassxc.gpg
      args:
        executable: /bin/bash
      register: gpg_convert
      changed_when: gpg_convert.rc == 0

    - name: Software | keepassxc | add keepassxc apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/keepassxc.gpg] https://ppa.launchpadcontent.net/phoerious/keepassxc/ubuntu {{ ansible_distribution_release }} main"
        state: present

    - name: Software | keepassxc | install keepassxc
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - keepassxc
