---
- name: Software | lynis | install lynis system audit packages
  ansible.builtin.apt:
    state: present
    pkg:
      - lynis

- name: Software | lynis | systemd service and timer for root
  ansible.builtin.copy:
    src: file/systemd/{{ item }}
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - lynis-audit.service
    - lynis-audit.timer
