---
- name: Software | lynis | install lynis system audit packages
  ansible.builtin.apt:
    state: present
    pkg:
      - lynis

- name: Software | lynis | cron job for root lynis audit
  ansible.builtin.cron:
    name: lynis_audit
    user: root
    special_time: reboot
    job: "sleep 400 && lynis audit system > /var/log/lynis-audit.log"
