---
- name: software | modern-unix | install various utilities
  apt:
    pkg:
      - fontconfig
      - bat
      - duf
      - lsd
      - ripgrep

- name: software | modern-unix | download latest release info for lsd nerd fonts
  command: curl https://github.com/ryanoasis/nerd-fonts/releases/latest
  args:
    warn: false
  register: fonts_download

- name: software | modern-unix | set fact extract fonts release
  set_fact:
    fonts_release: "{{ fonts_download | regex_search('(?<=/tag/)[^\"]*') }}"

- name: software | modern-unix | Print latest lsd nerd fonts release
  debug:
    var: fonts_release
    verbosity: 2

- name: software | modern-unix | Creates directory for lsd fonts
  file:
    path: /usr/local/share/fonts/lsd
    state: directory
    owner: root
    group: root
    mode: 0775

- name: software | modern-unix | download and install JetBrains and Ubuntu nerd fonts for lsd
  become: true
  become_method: sudo
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/{{ fonts_release }}/{{ item }}
    dest: /usr/local/share/fonts/lsd
    remote_src: yes
    mode: 0644
    owner: root
    group: root
  with_items:
    - JetBrainsMono.zip
    - Ubuntu.zip

- name: software | modern-unix | create cache for new fonts
  command: fc-cache -v -f
