---
# Install cool utilities specified under modern-unix plus zsh and nerd fonts
#

- name: software | modern-unix | install various utilities
  apt:
    pkg:
      - fontconfig
      - bat
      - duf
      - ripgrep
      - zsh

# Get latest release from Github api
# get tag line
# pluck JSON value
- name: software | lsd | download latest release info
  shell: |
    set -o pipefail
    curl --silent "https://api.github.com/repos/Peltoche/lsd/releases/latest" |
    grep '"tag_name":' |
    sed -E 's/.*"([^"]+)".*/\1/'
  args:
    warn: false
    executable: /bin/bash
  register: lsd_release
  changed_when: lsd_release.rc == 0

- name: software | lsd | Print latest release
  debug:
    var: lsd_release.stdout
    verbosity: 2

- name: software | lsd | install lsd program
  apt:
    deb: https://github.com/Peltoche/lsd/releases/download/{{ lsd_release.stdout }}/lsd_{{ lsd_release.stdout }}_amd64.deb

# Get latest release from Github api
# get tag line
# pluck JSON value
- name: software | modern-unix | download latest release info for lsd nerd fonts
  shell: |
    set -o pipefail
    curl --silent https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest |
    grep '"tag_name":' |
    sed -E 's/.*"([^"]+)".*/\1/'
  args:
    warn: false
    executable: /bin/bash
  register: fonts_release
  changed_when: fonts_release.rc == 0

- name: software | modern-unix | Print latest lsd nerd fonts release
  debug:
    var: fonts_release.stdout
    verbosity: 2

- name: software | modern-unix | Creates directory for lsd nerd fonts
  file:
    path: /usr/local/share/fonts/lsd
    state: directory
    owner: root
    group: root
    mode: 0775

- name: software | modern-unix | download and install fontawesome 6 | check https://fontawesome.com/download for link
  become: true
  become_method: sudo
  unarchive:
    src: https://use.fontawesome.com/releases/v6.2.0/fontawesome-free-6.2.0-desktop.zip
    dest: /usr/local/share/fonts/lsd
    remote_src: yes
    owner: root
    group: root
    mode: 0644

- name: software | modern-unix | download and install JetBrains and FiraCode nerd fonts
  become: true
  become_method: sudo
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/{{ fonts_release.stdout }}/{{ item }}
    dest: /usr/local/share/fonts/lsd
    remote_src: yes
    owner: root
    group: root
    mode: 0644
  with_items:
    - JetBrainsMono.zip
    - FiraCode.zip

- name: software | modern-unix | create cache for new fonts
  command: fc-cache -v -f
  register: create_cache
  changed_when: create_cache.rc == 0
