---
# Create nodejs environment for user - variables defined in host_vars

- name: Softeare | nodejs block
  when:
    - nodejs is defined
    - nodejs
  block:

    - name: Software | nodejs | install nodejs and npm 
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Software | nodejs | replace NODE_OPTIONS variable with empty value (is active only after terminal restart or reload)
      ansible.builtin.replace: 
        path: /home/bernhard/{{ item }} 
        regexp: "export NODE_OPTIONS='--disable-warning=ExperimentalWarning'"
        replace: "export NODE_OPTIONS="
      with_items:
        - .bashrc
        - .zshenv

    - name: Software | nodejs | Verify nvm installation.
      become: true 
      become_user: bernhard
      ansible.builtin.shell: |
        set -o pipefail
        export NODE_OPTIONS=
        npm --version
        node --version
      args:
        executable: /bin/bash
      register: nodejs_verify
      changed_when: nodejs_verify.rc == 0

    - name: Software | nodejs | display shell results
      ansible.builtin.debug:
        msg: 
          - "{{ nodejs_verify.stdout_lines }}"

    - name: Software | npm | Install git-split-diffs and tldr packages globally.
      community.general.npm:
        name: "{{ item }}"
        global: true
      with_items:
        - git-split-diffs
        - tldr
