---
- name: software | nvidia block
  block:
    - name: software | nvidia | display installed nvidia-kernel-common version 
      command: dpkg -l nvidia-kernel*
      register: nvidia_latest
      changed_when: nvidia_latest.rc == 0

    - name: software | nvidia | Print nvidia result
      debug:
        var: nvidia_latest.stdout
        verbosity: 2

    - name: software | nvidia | set fact nvidia_release
      set_fact:
        nvidia_release: "{{ nvidia_latest.stdout | regex_search('(?<=common-)[^\ ]*') }}"

    - name: software | nvidia | Print apt install statements
      debug:
        msg: "{{ item }}"
        verbosity: 2
      with_items:
        - "nvidia-utils-{{ nvidia_release }}"

    - name: software | nvidia | install nvidia utils
      become: true
      become_method: sudo
      apt: 
        pkg:
          - nvidia-utils-{{ nvidia_release }}
  when:
    - nvidia is defined
    - nvidia
