---
#
# See install doc: https://protonvpn.com/support/linux-ubuntu-vpn-setup/
#
- name: Software | protonvpn block
  when:
    - protonvpn is defined
    - protonvpn
  become: true
  become_method: ansible.builtin.sudo
  block:
    - name: Software | protonvpn | add protonvpn to apt cache
      ansible.builtin.apt:
        deb: https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_{{ protonvpn_version }}.deb
    #
    # Proton VPN Gnome Desktop metapackage
    # A metapackage that installs all necessary dependencies for Proton VPN on Gnome based desktops
    #
    - name: Software | protonvpn | install proton-vpn-gnome-desktop and prerequisites
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - proton-vpn-gnome-desktop
          - libayatana-appindicator3-1
          - gir1.2-ayatanaappindicator3-0.1
          - gnome-shell-extension-appindicator
        state: present

