---
- name: Software | tilix | create tilix schemes directory
  ansible.builtin.file:
    path: /home/{{ user_name }}/{{ item.dir }}
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0740
  with_items:
    - { dir: '.config/tilix' }
    - { dir: '.config/tilix/schemes' }

- name: Software | tilix | download tilix color schemes from github
  ansible.builtin.get_url:
    url: "https://git.io/{{ item.url }}"
    dest: "/home/{{ user_name }}/.config/tilix/schemes/{{ item.dest }}"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0644
  with_items:
    - { url: 'v7QVD', dest: 'argonaut.json' }
    - { url: 'v7Qav', dest: 'cobalt2.json' }
    - { url: 'v7Q2j', dest: 'dark-pastel.json' }
    - { url: 'v7QaW', dest: 'hipster-green.json' }
    - { url: 'v7QaN', dest: 'paul-millr.json' }
    - { url: 'v7QVZ', dest: 'thayer-bright.json' }
    - { url: 'v7Qag', dest: 'kibble.json' }

- name: Software | tilix | set tilix values in dconf
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: 'font', value: "'JetBrainsMono Nerd Font Light 16'" }
    - { key: 'visible-name', value: "'bpic'" }
