---
- name: Software | tilix | create tilix schemes directory
  ansible.builtin.file:
    path: /home/{{ user_name }}/{{ item.dir }}
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: "0740"
  with_items:
    - { dir: '.config/tilix' }
    - { dir: '.config/tilix/schemes' }

- name: Software | tilix | download tilix color schemes from github
  ansible.builtin.get_url:
    url: "https://codeberg.org/SnowCode/tilix-colors{{ item.url }}"
    dest: "/home/{{ user_name }}/.config/tilix/schemes/{{ item.dest }}"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: "0644"
  with_items:
    - { url: 'argonaut.json', dest: 'argonaut.json' }
    - { url: 'cobalt2.json', dest: 'cobalt2.json' }
    - { url: 'dark-pastel.json', dest: 'dark-pastel.json' }
    - { url: 'hipster-green.json', dest: 'hipster-green.json' }
    - { url: 'paul-millr.json', dest: 'paul-millr.json' }
    - { url: 'nord.json', dest: 'nord.json' }
    - { url: 'thayer-bright.json', dest: 'thayer-bright.json' }
    - { url: 'kibble.json', dest: 'kibble.json' }

- name: Software | tilix | set tilix values in dconf
  become: true
  become_user: "{{ user_name }}"
  community.general.dconf:
    key: "/com/gexperts/Tilix/profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d/{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: 'font', value: "'VictorMono Nerd Font Mono Regular 16'" }
    - { key: 'visible-name', value: "'bpic'" }
