---
# Create vim environment for user bernhard - variables defined in host_vars
#- name: users | bernhard | user name fact
#  set_fact:
#    user_name: 'bernhard'
#    group_name: 'users'

- name: Vim-task | recursivebly remove .vim/bundle directory to enable re-runs for {{ user_name }}
  ansible.builtin.file:
    path: /home/{{ user_name }}/.vim/bundle
    state: absent

- name: Vim | create vim directories for {{ user_name }}
  ansible.builtin.file:
    path: /home/{{ user_name }}/{{ item.dir }}
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0700
  with_items:
    - { dir: '.vim' }
    - { dir: '.vim/autoload' }
    - { dir: '.vim/colors' }
    - { dir: '.vim/ftplugin' }
    - { dir: '.vim/plugged' }

- name: Vim | copy vim dotfile for {{ user_name }}
  ansible.builtin.copy:
    src: users/vim/{{ item.src }}
    dest: /home/{{ user_name }}/{{ item.dest }}
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0600
  with_items:
    - { src: 'vimrc', dest: '.vimrc' }

- name: Vim | download filetype ftplugin vim files from github for {{ user_name }}
  become: true
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/vim/vim/master/runtime/ftplugin/{{ item.src }}"
    dest: "/home/{{ user_name }}/.vim/{{ item.src }}"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0600
  with_items:
    - { src: 'bash.vim' }
    - { src: 'conf.vim' }
    - { src: 'config.vim' }
    - { src: 'cpp.vim' }
    - { src: 'dircolors.vim' }
    - { src: 'fstab.vim' }
    - { src: 'gitconfig.vim' }
    - { src: 'gitignore.vim' }
    - { src: 'go.vim' }
    - { src: 'html.vim' }
    - { src: 'java.vim' }
    - { src: 'json.vim' }
    - { src: 'lynx.vim' }
    - { src: 'markdown.vim' }
    - { src: 'python.vim' }
    - { src: 'ruby.vim' }
    - { src: 'sh.vim' }
    - { src: 'sql.vim' }
    - { src: 'vim.vim' }
    - { src: 'yaml.vim' }

- name: Vim | download plug.vim & color vim files from github for {{ user_name }}
  become: true
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/{{ item.url }}"
    dest: "/home/{{ user_name }}/.vim/{{ item.dest }}"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0600
  with_items:
    - { url: 'junegunn/vim-plug/master/plug.vim', dest: 'autoload/plug.vim' }
    - { url: 'nanotech/jellybeans.vim/master/colors/jellybeans.vim', dest: 'colors/jellybeans.vim' }
    - { url: 'jaredgorski/SpaceCamp/master/colors/spacecamp.vim', dest: 'colors/spacecamp.vim' }
    - { url: 'morhetz/gruvbox/master/colors/gruvbox.vim', dest: 'colors/gruvbox.vim' }
    - { url: 'NLKNguyen/papercolor-theme/master/colors/PaperColor.vim', dest: 'colors/PaperColor.vim' }
    - { url: 'rafalbromirski/vim-aurora/master/colors/aurora.vim', dest: 'colors/aurora.vim' }
# see this website for colors: https://vimcolorschemes.com/?ref=linuxhandbook.com 
