---
# Create zsh environment for user root 
# zsh package is installed in utilities.yml
  
- name: Software | Zsh | Creates zsh directory in .config for root
  ansible.builtin.file:
    path: /root/.config/{{ item.dir }}
    state: directory
    owner: root
    group: root
    mode: "0775"
  with_items:
    - { dir: 'zsh' }

- name: Software | zsh | download install.zsh script for zap (zsh plugin manager)
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh
    dest: /tmp/zap-install.zsh
    owner: root
    group: root
    mode: "0755"

- name: Software | Zsh | Make zap install idempotent - remove ~/.local/share/zap directory for root
  ansible.builtin.file:
    path: /root/.local/share/zap
    state: absent

- name: Software | zsh | run zap-install.zsh script (checkout to ~/.local/share/zap)
  ansible.builtin.shell:
    cmd: /tmp/zap-install.zsh --branch release-v1 
  args:
    executable: /bin/zsh
  register: zap_run
  changed_when: zap_run.rc == 0

- name: Software | zsh | display zap-install result
  ansible.builtin.debug:
    msg: 
      - "{{ zap_run.stdout_lines }}"
    verbosity: 2
 
- name: Software | Zsh | copy individual zsh config files for {{ user_name }}
  ansible.builtin.copy:
    src: users/zsh/{{ item.src }}
    dest: /root/.config/zsh/{{ item.dest }}
    owner: root
    group: root
    mode: "0600"
  with_items:
    - { src: 'aliases.zsh', dest: 'aliases.zsh' }
    - { src: 'history.zsh', dest: 'history.zsh' }
    - { src: 'root-prompt.zsh', dest: 'prompt.zsh' }
    - { src: 'functions.zsh', dest: 'functions.zsh' }
    - { src: 'zshrc', dest: '.zshrc' }

- name: Software | Zsh | copy zshenv as dotfile for {{ user_name }}
  ansible.builtin.copy:
    src: users/zsh/{{ item.src }}
    dest: /root/{{ item.dest }}
    owner: root
    group: root
    mode: "0600"
  with_items:
    - { src: 'zshenv', dest: '.zshenv' }

- name: Software | Zsh | change shell to /bin/zsh - new login required
  ansible.builtin.shell:
    cmd: chsh -s $(which zsh)
  args:
    executable: /bin/bash
  register: new_shell
  changed_when: new_shell.rc == 0
