---
# Create zsh environment for user bernhard - variables defined in host_vars

- name: Zsh | software | install zsh packages
  ansible.builtin.apt:
    state: present
    pkg:
      - zsh
    
- name: Zsh | Creates zsh directory in .config for {{ user_name }}
  ansible.builtin.file:
    path: /home/{{ user_name }}/.config/{{ item.dir }}
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0775
  with_items:
    - { dir: 'zsh' }

- name: Software | zap | Download install script zap (plugin manager for zsh)
  ansible.builtin.shell: |
    set -o pipefail
    curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh \
      --output /tmp/zap-install.zsh
  args:
    executable: /bin/zsh
  register: zap_load
  changed_when: zap_load.rc == 0

- name: Software | zap | Change permission of install script
  ansible.builtin.file:
    path: /tmp/{{ item }}
    state: file
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755
  with_items:
    - zap-install.zsh

- name: Software | zap | install zsh plugin manager (zap
  ansible.builtin.script: /tmp/zap-install.zsh --branch release-v1
  register: zap_install
  changed_when: zap_install.rc == 0
  
- name: Zsh | copy individual zsh config files for {{ user_name }}
  ansible.builtin.copy:
    src: users/zsh/{{ item.src }}
    dest: /home/{{ user_name }}/.config/zsh/{{ item.dest }}
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0600
  with_items:
    - { src: 'aliases.zsh', dest: 'aliases.zsh' }
    - { src: 'history.zsh', dest: 'history.zsh' }
    - { src: 'prompt.zsh', dest: 'prompt.zsh' }
    - { src: 'functions.zsh', dest: 'functions.zsh' }
    - { src: 'zshrc', dest: '.zshrc' }

- name: Zsh | copy zshenv as dotfile for {{ user_name }}
  ansible.builtin.copy:
    src: users/zsh/{{ item.src }}
    dest: /home/{{ user_name }}/{{ item.dest }}
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0600
  with_items:
    - { src: 'zshenv', dest: '.zshenv' }

- name: Zsh | change shell to /bin/zsh - new login required
  ansible.builtin.shell:
    cmd: chsh -s $(which zsh)
  args:
    executable: /bin/zsh
  register: new_shell
  changed_when: new_shell.rc == 0
