---
# Create zsh environment for user bernhard - variables defined in host_vars

- name: zsh | software | install zsh packages
  apt:
    state: present
    pkg:
      - zsh
    
- name: zsh | {{ user_name }} | Creates zsh directory in .config
  file:
    path: /home/{{ user_name }}/.config/{{ item.dir }}
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0775
  with_items:
    - { dir: 'zsh' }
    - { dir: 'zsh/plugins' }

- name: zsh | {{ user_name }} | copy individual zsh config files
  copy:
    src: users/zsh/{{ item.src }}
    dest: /home/{{ user_name }}/.config/zsh/{{ item.dest }}
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0600
  with_items:
    - { src: 'shell-manager.zsh', dest: 'shell-manager.zsh' }
    - { src: 'aliases.zsh', dest: 'aliases.zsh' }
    - { src: 'completion.zsh', dest: 'completion.zsh' }
    - { src: 'history.zsh', dest: 'history.zsh' }
    - { src: 'vim-mode.zsh', dest: 'vim-mode.zsh' }
    - { src: 'prompt.zsh', dest: 'prompt.zsh' }
    - { src: 'bash-functions.zsh', dest: 'bash-functions.zsh' }
    - { src: 'zshenv', dest: 'zshenv' }
    - { src: 'zshrc', dest: '.zshrc' }

- name: zsh | {{ user_name }} | copy dotfiles
  copy: 
    src: /home/{{ user_name }}/.config/zsh/{{ item.src }}
    dest: /home/{{ user_name }}/{{ item.dest }}
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0600
  with_items:
    - { src: 'zshenv', dest: '.zshenv' }
