---
- name: Software | vscodium block
  become: true
  become_method: sudo
  when:
    - vscodium is defined
    - vscodium
  block:
    #
    # apt-key is deprecated - use curl to get the gpg key and write it to /usr/share/keyrings directory
    #
    - name: Software | vscodium | add vscodium gpg key to keyring file
      ansible.builtin.shell: |
        set -o pipefail
        curl -fsSL https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | \
        sudo gpg --dearmor | \
        sudo tee /etc/apt/trusted.gpg.d/vscodium.gpg > /dev/null
      args:
        executable: /bin/bash
      register: vscodium_gpgkey
      changed_when: vscodium_gpgkey.rc == 0

    - name: Software | vscodium | add vscodium apt repository
      apt_repository:
        filename: vscodium
        repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/vscodium.gpg] https://download.vscodium.com/debs vscodium main'
        state: present

    - name: Software | vscodium | install codium
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - codium
        state: present
