#!/bin/bash
#
# script to kickstart a new desktop by installing git python ansible
#
apt update
#
# install git in case its missing
#
apt install -y git
#
apt install -y python3 python-is-python3 python3-pip
#
apt install -y ansible ansible-base
#
apt install -y yamllint ansible-lint
#
echo -n "\nInstalled versions: "
echo -n "\n "
python --version
ansible --version
yamllint --version
ansible-lint --version
