#!/bin/bash
#
# script to kickstart a new desktop by installing git python ansible
# from the ansible repository for latest version
#
apt install software-properties-common
apt-add-repository --yes ppa:ansible/ansible
apt-get update
apt install -y ansible ansible-base

#
# install git in case its missing
#
apt install -y git
#
apt install -y python3 python3-pip
#

echo -n "\nInstalled versions: "
echo -n "\n "
python --version
ansible --version
