#!/bin/bash
#
# script to kickstart a new desktop by installing git python ansible
# from the ansible repository for latest version
#
#
# install git in case its missing
#
apt install -y git
#
apt install -y python3 python3-pip
#
# install ansible with pip3 (ansible with apt does not work)
pip3 install ansible

echo -n "\nInstalled versions: "
echo -n "\n "
python3 --version
ansible --version
