ansible_passwd: $y$j9T$iUenE9kyccSKeW92NPKqK0$y1TRK7DGD4HUNdAPyUtGADFZzTw.oQr7hb3Thkqg1i1
wifi_passwd: $6$eREzcN4Kbmf.dXrF$LHKmD1564mQNdgXdCX3js1P49uZRoDKUfhDzs1uY5uk2OTw.yt5xSEqQ5DxqpOls.OH8qsD6BMBSZMp3qtUd.
