---
- name: run all tasks for base role
  block:

#    - name: include vars file
#      tags: always
#      include_vars: vault-secrets.yml

    # Make sure users exist on the system
    - import_tasks: users/root.yml
    - import_tasks: users/bernhard.yml
#    - import_tasks: users/ansible.yml
#    - import_tasks: users/ubuntu.yml

    # Set up the ansible environment
    - import_tasks: system_setup/ansible_setup.yml
    - import_tasks: system_setup/mdraid.yml
    - import_tasks: system_setup/idmapd.yml
    - import_tasks: system_setup/bluetooth.yml

    # install software
    - import_tasks: software/utilities.yml
    - import_tasks: software/tmux.yml
    - import_tasks: software/modern-unix
    - import_tasks: software/tilix.yml
    - import_tasks: software/java.yml
    - import_tasks: software/pkg_management.yml
    - import_tasks: software/development.yml
    - import_tasks: software/snap.yml

    # Perform remaining tasks:
    - import_tasks: system_setup/clock.yml
    - import_tasks: system_setup/cron.yml
    - import_tasks: system_setup/logging.yml
    - import_tasks: system_setup/microcode.yml
#  - import_tasks: system_setup/openssh.yml

  rescue:
    - name: set fact to true if tasks failed
      set_fact: task_failed=true
