---
- name: Run all tasks for base role
  when:
    - task_failed is not defined 
  block:

    # install software required by users
    - name: Install LSD software
      ansible.builtin.import_tasks:
        file: software/lsd.yml
    - name: Configure tilix terminal
      ansible.builtin.import_tasks:     
        file: software/tilix.yml

    # Make sure users exist on the system
    - name: Configure user root
      ansible.builtin.import_tasks:    
        file: users/root.yml
    - name: Configure user bernhard
      ansible.builtin.import_tasks:    
        file: users/bernhard.yml
    - name: Configure user marlies
      ansible.builtin.import_tasks:    
        file: users/marlies.yml
    - name: Create user ubuntu
      ansible.builtin.import_tasks:    
        file: users/ubuntu.yml

    # Fix some problems
    #    - name: Mdraid fix
    #  ansible.builtin.import_tasks: 
    #    file: system_setup/mdraid.yml
    #- name: Idmapd fixes
    #  ansible.builtin.import_tasks: 
    #    file: system_setup/idmapd.yml
    - name: Add fitting bluetooth driver
      ansible.builtin.import_tasks: 
        file: system_setup/bluetooth.yml

    # install software
#    - name: Install firefox             # errors with snap remove command!
#      ansible.builtin.import_tasks:    
#        file: software/firefox.yml
    - name: Install brave-browser
      ansible.builtin.import_tasks: 
        file: software/brave.yml
          #    - name: Install clamav virus scanner
          # ansible.builtin.import_tasks: 
          # file: software/clamav.yml
          #- name: Install lynis audit software
          # ansible.builtin.import_tasks: 
          # file: software/lynis.yml
    - name: Install several utilities
      ansible.builtin.import_tasks: 
        file: software/utilities.yml

    # Perform remaining tasks
    - name: Configure grub
      ansible.builtin.import_tasks: 
        file: system_setup/grub.yml
    - name: Configure clock
      ansible.builtin.import_tasks: 
        file: system_setup/clock.yml
    - name: Set cron jobs
      ansible.builtin.import_tasks: 
        file: system_setup/cron.yml
    - name: Configure logging
      ansible.builtin.import_tasks: 
        file: system_setup/logging.yml
    - name: Fix for microcode
      ansible.builtin.import_tasks: 
      file: system_setup/microcode.yml
      
#  - import_tasks: system_setup/openssh.yml

  rescue:
    - name: Set fact to true if tasks failed
      ansible.builtin.set_fact:
        task_failed: true
      
 
