---
- block:
  # Make sure users exist on the system
  - import_tasks: users/bpic.yml
  - import_tasks: users/root.yml
  - import_tasks: users/ansible.yml

  # Set up the ansible environment
  - import_tasks: ansible_setup.yml

  # install software
  - import_tasks: software/repositories.yml
  - import_tasks: software/development.yml
  - import_tasks: software/pip.yml
  - import_tasks: software/utilities.yml

  # Perform remaining tasks:
  - import_tasks: system_setup/clock.yml
  - import_tasks: system_setup/logging.yml
  - import_tasks: system_setup/memory.yml
  - import_tasks: system_setup/microcode.yml
  - import_tasks: system_setup/openssh.yml

  rescue:
    - set_fact: task_failed=true
