---
- name: ansible setup | install required packages
  apt:
    pkg:
      - acl
      - dconf-cli
      - python3-psutil
    state: present

- name: ansible setup | create ansible log file
  file:
    path: /var/log/ansible.log
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0664
    state: touch
  changed_when: False

- name: ansible setup | add logrotate config for ansible log file
  copy:
    src: files/ansible_setup/logrotate
    dest: /etc/logrotate.d/ansible
    owner: root
    group: root
    mode: 0644

- name: ansible setup | remove default ansible directory (/etc/ansible) from host
  file:
    path: /etc/ansible
    state: absent
