---
#- name: system setup | cron | schedule automatic ansible provisioning
#  cron:
#    name: "ansible-pull provision"
#    user: ansible
#    minute: "*/30"
#    job: "sudo /usr/bin/ansible-pull -o -U https://github.com/agingskier/ansible_pull_desktop.git > /dev/null"

#- name: system setup | cron | schedule ansible cleanup at boot
#  cron:
#    name: "ansible refresh at boot"
#    user: ansible
#    special_time: reboot
#    job: "/bin/rm -rf /home/ansible/.ansible"

- name: system setup | cron | schedule log reduction
  cron:
    name: "logfile reduction"
    user: root
    special_time: reboot
    job: "sleep 300 && journalctl --vacuum-time=7days"

- name: system setup | cron | plocate database
  cron:
    name: "plocate database"
    user: root
    special_time: reboot
    job: "sleep 200 && updatedb"
