---
- name: System setup | systemd | systemd logfile reduction service and timer for root
  ansible.builtin.copy:
    src: file/systemd/{{ item }}
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - logfile-reduction.service
    - logfile-reduction.timer
