---
- name: System setup | systemd | systemd logfile reduction service and timer for root
  ansible.builtin.copy:
    src: file/systemd/{{ item }}
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - logfile-reduction.service
    - logfile-reduction.timer

- name: System_setup | systemd units | systemd logfile reduction service and timer
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: system
    daemon_reload: true
  with_items:
    - logfile-reduction.timer
    - logfile-reduction.service
