---
- name: System setup | logging | adjust retention period
  ansible.builtin.lineinfile:
    dest: "/etc/systemd/journald.conf"
    regexp: "^#MaxFileSec="
    line: "MaxFileSec=5day"
  notify: Restart journald
