---
- name: system setup | logging | adjust retention period
  tags: systemd,journal,journald,sysctl,system setup
  lineinfile:
    dest: "/etc/systemd/journald.conf"
    regexp: "^#MaxFileSec="
    line: "MaxFileSec=5day"
  register: restart_journald
