---
- name: system setup | patch mdraid error | install missing packages
  tags: packages,system,settings
  apt:
    state: present
    pkg:
      - libblockdev-crypto2
      - libblockdev-mdraid2
  notify: restart_udisks2
