---
- name: System setup | patch mdraid error | install missing packages for Multiple Disk RAID
  ansible.builtin.apt:
    state: present
    pkg:
      - libblockdev-crypto2
      - libblockdev-mdraid2
  notify: Restart udisks2
