- name: system setup | microcode | install package for intel
  tags: cpu,intel,microcode,system setup
  apt:
    name: intel-microcode
    state: latest
  when:
    - microcode_intel_install is defined
    - microcode_intel_install == true
