---
- name: System setup | microcode | MDS cup bug with SMT on - install intel-microcode package
  apt:
    name: intel-microcode
    state: present
  when:
    - microcode_intel_install is defined
    - microcode_intel_install
