---
- name: System setup | openssh | install or update daemon package
  ansible.builtin.apt:
    name: openssh-server
    state: present
  notify: Restart_sshd

- name: System setup | openssh | enable daemon
  ansible.builtin.service:
    name: ssh
    enabled: true
    state: started

- name: System setup | openssh | generate sshd_config file from template
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: Restart_sshd
